///////////////////////////////////////////////////////////////////////////////
// Files generated by the tests here are anaylzed by the jupyter notebook
// analyze_transmit_filter_chain.ipynb
///////////////////////////////////////////////////////////////////////////////

#include "gtest/gtest.h"
#include "../src/PhoenixSketch/SDT.h"
#include <sys/time.h>

float32_t get_max(float32_t *d, uint32_t Nsamples){
    float32_t max = -1e6;
    for (size_t i = 0; i<Nsamples; i++){
        if (d[i] > max)
            max = d[i];
    }
    return max;
}

int CreateIQToneWithPhase(float *I, float *Q, int Nsamples, int sampleRate_Hz,
                int tone_Hz, int phase_index,float amplitude){
    float oneoverfs = 1.0 / (float)sampleRate_Hz;
    for (int i=0;i<Nsamples;i++){
        I[i] = amplitude*cos(-TWO_PI*(float)(i+phase_index)*oneoverfs*tone_Hz);
        Q[i] = amplitude*sin(-TWO_PI*(float)(i+phase_index)*oneoverfs*tone_Hz);
    }
    return (phase_index+Nsamples);
}

int AddIQToneWithPhase(float *I, float *Q, int Nsamples, int sampleRate_Hz,
                int tone_Hz, int phase_index,float amplitude){
    float oneoverfs = 1.0 / (float)sampleRate_Hz;
    for (int i=0;i<Nsamples;i++){
        I[i] += amplitude*cos(-TWO_PI*(float)(i+phase_index)*oneoverfs*tone_Hz);
        Q[i] += amplitude*sin(-TWO_PI*(float)(i+phase_index)*oneoverfs*tone_Hz);
    }
    return (phase_index+Nsamples);
}

void CreateTone(float *buf, int Nsamples, int sampleRate_Hz, float tone_Hz){
    float oneoverfs = 1.0 / (float)sampleRate_Hz;
    for (int i=0;i<Nsamples;i++){
        buf[i] = 0.5*sin(TWO_PI*tone_Hz*(float)i*oneoverfs);
    }
}

void CreateIQTone(float *I, float *Q, int Nsamples, int sampleRate_Hz, float tone_Hz){
    float oneoverfs = 1.0 / (float)sampleRate_Hz;
    for (int i=0;i<Nsamples;i++){
        I[i] = 0.5*cos(TWO_PI*tone_Hz*(float)i*oneoverfs);
        Q[i] = 0.5*sin(TWO_PI*tone_Hz*(float)i*oneoverfs);
    }
}

void CreateIQChirp(float *I, float *Q, int Nsamples, int sampleRate_Hz){
    float oneoverfs = 1.0 / (float)sampleRate_Hz;
    for (int i=0;i<Nsamples;i++){
        I[i] = 0.5*cos(-TWO_PI*(float)i*oneoverfs*(200+(float)i/2048*1000));
        Q[i] = 0.5*sin(-TWO_PI*(float)i*oneoverfs*(200+(float)i/2048*1000));
    }
}

void CreateDoubleTone(float *buf, int Nsamples, int sampleRate_Hz, 
                        float tone1_Hz,float tone2_Hz){
    float oneoverfs = 1.0 / (float)sampleRate_Hz;
    for (int i=0;i<Nsamples;i++){
        buf[i] = 0.5*sin(TWO_PI*tone1_Hz*(float)i*oneoverfs)
                +0.5*sin(TWO_PI*tone2_Hz*(float)i*oneoverfs);
    }
}

void WriteFile(float32_t *data, char *fname, int N){
    FILE *file = fopen(fname, "w");
    for (size_t i = 0; i < N; i++) {
        fprintf(file, "%zu,%7.6f\n", i,data[i]);
    }
    fclose(file);
}

void WriteIQFile(float32_t *I, float32_t *Q, char *fname, int N){
    FILE *file = fopen(fname, "w");
    for (size_t i = 0; i < N; i++) {
        fprintf(file, "%zu,%7.6f,%7.6f\n", i,I[i],Q[i]);
    }
    fclose(file);
}

void WriteBiquadFilterState(arm_biquad_casd_df1_inst_f32 *bq, char *fname){
    FILE *file = fopen(fname, "w");
    fprintf(file,"Num stages:        %d\n",bq->numStages);
    fprintf(file,"pState pointer:    %p\n",(void *)bq->pState);
    fprintf(file,"pCoeffs pointer:   %p\n",(void *)bq->pCoeffs);
    fprintf(file, "Stage, pstate 1,2,3,4\n");
    for (int i=0; i<bq->numStages; i++){
        fprintf(file,"    %d,%6.5f,%6.5f,%6.5f,%6.5f\n",i,
                bq->pState[0],
                bq->pState[1],
                bq->pState[2],
                bq->pState[3]);
    }
    fprintf(file, "Stage, coeffs 1,2,3,4,5\n");
    for (int i=0; i<bq->numStages; i++){
        fprintf(file,"    %d,%6.5f,%6.5f,%6.5f,%6.5f,%6.5f\n",i,
                bq->pCoeffs[5*i+0],
                bq->pCoeffs[5*i+1],
                bq->pCoeffs[5*i+2],
                bq->pCoeffs[5*i+3],
                bq->pCoeffs[5*i+4]);
    }
    fclose(file);
}

void PrepareIQDataFsOver4Tone(float *I, float *Q, float *buffer_spec_FFT){
    for (size_t i = 0; i<128; i++){
        I[4*i+0] = +1;
        I[4*i+1] =  0;
        I[4*i+2] = -1;
        I[4*i+3] =  0;

        Q[4*i+0] =  0;
        Q[4*i+1] = -1;
        Q[4*i+2] =  0;
        Q[4*i+3] = +1;
    }
    for (size_t i = 0; i < SPECTRUM_RES; i++) { 
        buffer_spec_FFT[i * 2] =      I[i]; 
        buffer_spec_FFT[i * 2 + 1] =  Q[i];
    }
}

void PrepareIQDataFsOver4Tone(float *I, float *Q, uint32_t Nsamples){
    for (size_t i = 0; i<Nsamples/4; i++){
        I[4*i+0] = +1;
        I[4*i+1] =  0;
        I[4*i+2] = -1;
        I[4*i+3] =  0;

        Q[4*i+0] =  0;
        Q[4*i+1] = -1;
        Q[4*i+2] =  0;
        Q[4*i+3] = +1;
    }
}

int32_t frequency_to_bin(float freq, int32_t Nbins, int32_t SampleRate){
    return (Nbins/2 + (int32_t)( (float)Nbins * freq / (float)SampleRate ));
}


void add_second_tone(float *I, float *Q, float tone2_Hz, int sampleRate_Hz, int Nsamples){
    float I2[Nsamples];
    float Q2[Nsamples];
    CreateIQTone(I2, Q2, Nsamples, sampleRate_Hz, tone2_Hz);
    for (int i =0; i<Nsamples; i++){
        I[i] += I2[i];
        Q[i] += Q2[i];
    }
}

void add_comb(float *I, float *Q, int sampleRate_Hz, int Nsamples){
    float tone2_Hz = 96000-10*96000/512;
    //add_second_tone(I,Q, tone2_Hz, sampleRate_Hz, Nsamples);
    //tone2_Hz = 96000-50*96000/512;
    //add_second_tone(I,Q, tone2_Hz, sampleRate_Hz, Nsamples);
    //tone2_Hz = 96000-90*96000/512;
    //add_second_tone(I,Q, tone2_Hz, sampleRate_Hz, Nsamples);
    //tone2_Hz = 96000-130*96000/512;
    //add_second_tone(I,Q, tone2_Hz, sampleRate_Hz, Nsamples);
    //tone2_Hz = 96000-210*96000/512;
    //add_second_tone(I,Q, tone2_Hz, sampleRate_Hz, Nsamples);
    tone2_Hz = 96000-290*96000/512;
    add_second_tone(I,Q, tone2_Hz, sampleRate_Hz, Nsamples);
    tone2_Hz = 96000-370*96000/512;
    add_second_tone(I,Q, tone2_Hz, sampleRate_Hz, Nsamples);
    tone2_Hz = 96000-450*96000/512;
    add_second_tone(I,Q, tone2_Hz, sampleRate_Hz, Nsamples);
}

TEST(TransmitChain, DecimateByX){
    // For all the decimate by N tests, run two blocks through because the state
    // vector for the FIR filter starts at zero for the first block, which introduces
    // artifacts
    uint32_t Nsamples = 2048*2;
    uint32_t sampleRate_Hz = 192000;
    float I[Nsamples];
    float Q[Nsamples];
    float tone_Hz;
    tone_Hz = -10*96000/512;

    CreateIQTone(I, Q, Nsamples, sampleRate_Hz, tone_Hz);
    add_comb(I,Q,sampleRate_Hz,Nsamples);
    WriteIQFile(I,Q,"TXDecimateBy4_original_IQ.txt",Nsamples);
    InitializeTransmitFilters(&TXfilters);
    DataBlock data;
    data.I = I;
    data.Q = Q;
    TXDecimateBy4(&data,&TXfilters);
    WriteIQFile(I,Q,"TXDecimateBy4_decimated_IQ_pass1.txt",Nsamples/4/2);
    data.I = &I[2048];
    data.Q = &Q[2048];
    TXDecimateBy4(&data,&TXfilters);
    WriteIQFile(&I[2048],&Q[2048],"TXDecimateBy4_decimated_IQ_pass2.txt",Nsamples/4/2);

    CreateIQTone(I, Q, 1024, sampleRate_Hz/4, tone_Hz);
    add_comb(I,Q,sampleRate_Hz/4,1024);
    WriteIQFile(I,Q,"TXDecimateBy2_original_IQ.txt",1024);
    data.I = I;
    data.Q = Q;
    TXDecimateBy2(&data,&TXfilters);
    WriteIQFile(I,Q,"TXDecimateBy2_decimated_IQ_pass1.txt",256);
    data.I = &I[512];
    data.Q = &Q[512];
    TXDecimateBy2(&data,&TXfilters);
    WriteIQFile(&I[512],&Q[512],"TXDecimateBy2_decimated_IQ_pass2.txt",256);

    CreateIQTone(I, Q, 512, sampleRate_Hz/8, tone_Hz);
    add_comb(I,Q,sampleRate_Hz/8,512);
    WriteIQFile(I,Q,"TXDecimateBy16_original_IQ.txt",512);
    data.I = I;
    data.Q = Q;
    TXDecimateBy2(&data,&TXfilters);
    WriteIQFile(I,Q,"TXDecimateBy16_decimated_IQ_pass1.txt",128);
    data.I = &I[256];
    data.Q = &Q[256];
    TXDecimateBy2(&data,&TXfilters);
    WriteIQFile(&I[256],&Q[256],"TXDecimateBy16_decimated_IQ_pass2.txt",128);

    EXPECT_EQ(1,1);
}

float32_t getmax(float32_t *data, uint32_t N){
    float32_t amp = -FLT_MAX;
    for (size_t i=0; i<N; i++){
        if (data[i] > amp) amp = data[i];
    }
    return amp;
}

TEST(TransmitChain, DecimateByXTransmissionResponse){
    // For all the decimate by N tests, run two blocks through because the state
    // vector for the FIR filter starts at zero for the first block, which introduces
    // artifacts
    uint32_t Nsamples = 2048*2;
    uint32_t sampleRate_Hz = 192000;
    float I[Nsamples];
    float Q[Nsamples];

    float32_t fmin = 0.0;
    float32_t fmax = 90000.0;
    uint32_t Npoints = 101;
    float32_t fstep = (fmax - fmin)/(float32_t)Npoints;
    float32_t gainx4[Npoints];
    float32_t gainx2[Npoints];
    float32_t gainx2x2[Npoints];
    float32_t freq[Npoints];   

    InitializeTransmitFilters(&TXfilters);

    float32_t amp;
    DataBlock data;
    for (int i = 0; i<Npoints; i++){
        freq[i] = fmin + (float32_t)i*fstep;

        CreateIQTone(I, Q, Nsamples, sampleRate_Hz, freq[i]);

        data.I = I;
        data.Q = Q;
        TXDecimateBy4(&data,&TXfilters);
        data.I = &I[2048];
        data.Q = &Q[2048];
        TXDecimateBy4(&data,&TXfilters);
        
        amp = getmax(&I[2048],Nsamples/4/2);
        gainx4[i] = amp/0.5;
    }
    WriteIQFile(freq,gainx4,"TXDecimateBy4_passband.txt",Npoints);

    CreateIQTone(I, Q, 1024, 192000/4, 20000);
    data.I = I;
    data.Q = Q;
    TXDecimateBy2(&data,&TXfilters);
    data.I = &I[512];
    data.Q = &Q[512];
    TXDecimateBy2(&data,&TXfilters);
    WriteIQFile(&I[512],&Q[512],"TXDecimateBy2_6000.txt",256);
    for (int i = 0; i<Npoints; i++){
        freq[i] = fmin + (float32_t)i*fstep;

        CreateIQTone(I, Q, 1024, 192000/4, freq[i]);

        data.I = I;
        data.Q = Q;
        TXDecimateBy2(&data,&TXfilters);
        data.I = &I[512];
        data.Q = &Q[512];
        TXDecimateBy2(&data,&TXfilters);

        gainx2[i] = getmax(&I[512+128],128)/0.5;
    }
    WriteIQFile(freq,gainx2,"TXDecimateBy2_passband.txt",Npoints);


    for (int i = 0; i<Npoints; i++){
        freq[i] = fmin + (float32_t)i*fstep;

        CreateIQTone(I, Q, 512, 192000/8, freq[i]);

        data.I = I;
        data.Q = Q;
        TXDecimateBy2(&data,&TXfilters);
        data.I = &I[256];
        data.Q = &Q[256];
        TXDecimateBy2(&data,&TXfilters);

        gainx2x2[i] = getmax(&I[256+64],64)/0.5;
    }
    WriteIQFile(freq,gainx2x2,"TXDecimateBy2x2_passband.txt",Npoints);

    EXPECT_EQ(1,1);
}

TEST(TransmitChain, HilbertPassband){
    uint32_t Nsamples = 128*2;
    uint32_t sampleRate_Hz = 192000/4/2/2;
    float I[Nsamples];
    float Q[Nsamples];
    DataBlock data;
    data.I = I;
    data.Q = Q;

    float32_t fmin = 0.0;
    float32_t fmax = 6000.0;
    uint32_t Npoints = 101;
    float32_t fstep = (fmax - fmin)/(float32_t)Npoints;
    float32_t hilbertI[Npoints];
    float32_t hilbertQ[Npoints];
    float32_t mag[Npoints];
    float32_t freq[Npoints];   

    InitializeTransmitFilters(&TXfilters);

    float32_t amp;
    for (int i = 0; i<Npoints; i++){
        freq[i] = fmin + (float32_t)i*fstep;
        CreateIQTone(I, Q, Nsamples, sampleRate_Hz, freq[i]);
        arm_copy_f32(I,Q,Nsamples);

        data.I = I;
        data.Q = Q;
        HilbertTransform(&data,&TXfilters);
        data.I = &I[128];
        data.Q = &Q[128];
        HilbertTransform(&data,&TXfilters);

        mag[i] = 0;
        for (int j=0; j<Nsamples/2; j++){
            mag[i] += sqrtf(Q[128+j]*Q[128+j] + I[128+j]*I[128+j]);
        }
        mag[i] = mag[i]/(Nsamples/2);
        
        if (i == Npoints-1){
            float32_t angle[Nsamples/2];
            float32_t mag =0;
            for (int j=0; j<Nsamples/2; j++){
                angle[j] = atan2f(Q[128+j],I[128+j]);
            }
            WriteFile(angle,"TXHilbert_angle.txt",Nsamples/2);
            WriteIQFile(&I[128],&Q[128],"TXHilbert_post_IQ.txt",128);
        }
        hilbertI[i] = getmax(&I[128],128)/0.5;
        hilbertQ[i] = getmax(&Q[128],128)/0.5;
    }
    WriteIQFile(freq,hilbertI,"TXHilbertI_passband.txt",Npoints);
    WriteIQFile(freq,hilbertQ,"TXHilbertQ_passband.txt",Npoints);
    WriteIQFile(freq,mag,"TXHilbertIQ_mag.txt",Npoints);    

    EXPECT_EQ(1,1);
}

void TXEQ_filter_tone(float32_t toneFreq_Hz, float32_t *gain){
   
    uint32_t Nsamples = 256;
    float I[Nsamples];
    float Q[Nsamples];
    float32_t sampleRate_Hz = SR[SampleRate].rate/RXfilters.DF;
    DataBlock data;
    data.I = I;
    data.Q = Q;
    data.N = Nsamples;
    data.sampleRate_Hz = sampleRate_Hz;
    InitializeFilters(SPECTRUM_ZOOM_1, &RXfilters);
    uint32_t phase = 0;
    // Need four iterations for the filter to "warm up" -- i.e., for the IIR filter state vector
    // to reach equilibrium -- at the lowest bands
    phase = CreateIQToneWithPhase(I, Q, Nsamples, sampleRate_Hz, toneFreq_Hz, phase, 0.1);
    BandEQ(&data, &RXfilters, TX);
    
    phase = CreateIQToneWithPhase(I, Q, Nsamples, sampleRate_Hz, toneFreq_Hz, phase, 0.1);
    BandEQ(&data, &RXfilters, TX);

    phase = CreateIQToneWithPhase(I, Q, Nsamples, sampleRate_Hz, toneFreq_Hz, phase, 0.1);
    BandEQ(&data, &RXfilters, TX);

    phase = CreateIQToneWithPhase(I, Q, Nsamples, sampleRate_Hz, toneFreq_Hz, phase, 0.1);
    BandEQ(&data, &RXfilters, TX);

    // Find the max value in I
    float32_t amp = -FLT_MAX;
    for (size_t i=0; i<256; i++){
        if (I[i] > amp) amp = I[i];
    }
    *gain = amp/0.1;
}

void TXEQ_filter_tone_new(float32_t toneFreq_Hz, float32_t *gain){
   
    uint32_t Nsamples = 256;
    float I[Nsamples];
    float Q[Nsamples];
    float32_t sampleRate_Hz = SR[SampleRate].rate/RXfilters.DF;
    DataBlock data;
    data.I = I;
    data.Q = Q;
    data.N = Nsamples;
    data.sampleRate_Hz = sampleRate_Hz;
    InitializeFilters(SPECTRUM_ZOOM_1, &RXfilters);

    uint32_t phase = 0;
    // Need four iterations for the filter to "warm up" -- i.e., for the IIR filter state vector
    // to reach equilibrium -- at the lowest bands
    phase = CreateIQToneWithPhase(I, Q, Nsamples, sampleRate_Hz, toneFreq_Hz, phase, 0.1);
    BandEQ(&data,&RXfilters,TX);
    
    phase = CreateIQToneWithPhase(I, Q, Nsamples, sampleRate_Hz, toneFreq_Hz, phase, 0.1);
    BandEQ(&data,&RXfilters,TX);
    
    phase = CreateIQToneWithPhase(I, Q, Nsamples, sampleRate_Hz, toneFreq_Hz, phase, 0.1);
    BandEQ(&data,&RXfilters,TX);
    
    phase = CreateIQToneWithPhase(I, Q, Nsamples, sampleRate_Hz, toneFreq_Hz, phase, 0.1);
    BandEQ(&data,&RXfilters,TX);
    
    // Find the max value in I
    float32_t amp = -FLT_MAX;
    for (size_t i=0; i<256; i++){
        if (I[i] > amp) amp = I[i];
    }
    *gain = amp/0.1;
}


TEST(TransmitChain, TransmitEQPlotPassbands){
    // Generate a bunch of tones between fmin and fmax. Measure the output of
    // the filtered data for each tone. Measure the passband in this way.

    float32_t fmin = 100.0;
    float32_t fmax = 8000.0;
    uint32_t Npoints = 401;
    float32_t fstep = (fmax - fmin)/(float32_t)Npoints;
    float32_t gain[Npoints];
    float32_t freq[Npoints];
    char strbuf[50];

    for (int i = 0; i<Npoints; i++){
        freq[i] = fmin + (float32_t)i*fstep;
        TXEQ_filter_tone(freq[i], &gain[i]);
    }
    sprintf(strbuf,"TransmitEQ_orig.txt");
    WriteIQFile(freq,gain,strbuf,Npoints);

    for (int i = 0; i<Npoints; i++){
        freq[i] = fmin + (float32_t)i*fstep;
        TXEQ_filter_tone_new(freq[i], &gain[i]);
    }
    sprintf(strbuf,"TransmitEQ_new.txt");
    WriteIQFile(freq,gain,strbuf,Npoints);
}

TEST(TransmitChain, InterpolateByN){
    uint32_t Nsamples = 128*2;
    uint32_t sampleRate_Hz = 192000/16;
    float I[Nsamples*2];  // Make buffer larger for in-place interpolation
    float Q[Nsamples*2];
    float tone_Hz;
    tone_Hz = 12000/32;
    tone_Hz = 12000/4;
    DataBlock data;
    data.I = I;
    data.Q = Q;
    data.N = 128;
    data.sampleRate_Hz = sampleRate_Hz;

    InitializeTransmitFilters(&TXfilters);

    CreateIQTone(I, Q, Nsamples, sampleRate_Hz, tone_Hz);
    WriteIQFile(I,Q,"TXInterpolateBy2x2_original_IQ.txt",Nsamples);
    TXInterpolateBy2Again(&data,&TXfilters);
    WriteIQFile(data.I,data.Q,"TXInterpolateBy2x2_interpolated_IQ_pass1.txt",256);

    CreateIQTone(I, Q, Nsamples, sampleRate_Hz, tone_Hz);
    data.I = &I[128];
    data.Q = &Q[128];
    data.N = 128;  // Reset N before second call
    data.sampleRate_Hz = sampleRate_Hz;
    TXInterpolateBy2Again(&data,&TXfilters);
    WriteIQFile(data.I,data.Q,"TXInterpolateBy2x2_interpolated_IQ_pass2.txt",256);


    Nsamples = 256*2;
    sampleRate_Hz = 192000/8;
    float I2[Nsamples*2];  // Make buffer larger for in-place interpolation
    float Q2[Nsamples*2];
    float Iout2[512];
    float Qout2[512];
    data.I = I2;
    data.Q = Q2;
    data.N = 256;
    data.sampleRate_Hz = sampleRate_Hz;
    tone_Hz = 24000/4;
    CreateIQTone(I2, Q2, Nsamples, sampleRate_Hz, tone_Hz);
    WriteIQFile(I2,Q2,"TXInterpolateBy2_original_IQ.txt",Nsamples);
    TXInterpolateBy2(&data,&TXfilters);
    WriteIQFile(data.I,data.Q,"TXInterpolateBy2_interpolated_IQ_pass1.txt",512);

    CreateIQTone(I2, Q2, Nsamples, sampleRate_Hz, tone_Hz);
    data.I = &I2[256];
    data.Q = &Q2[256];
    data.N = 256;
    data.sampleRate_Hz = sampleRate_Hz;
    TXInterpolateBy2(&data,&TXfilters);
    WriteIQFile(data.I,data.Q,"TXInterpolateBy2_interpolated_IQ_pass2.txt",512);


    Nsamples = 512*2;
    sampleRate_Hz = 192000/4;
    float I4[Nsamples*2];
    float Q4[Nsamples*2];
    //float Iout4[2048];
    //float Qout4[2048];
    tone_Hz = 24000/4;
    CreateIQTone(I4, Q4, Nsamples, sampleRate_Hz, tone_Hz);
    WriteIQFile(I4, Q4,"TXInterpolateBy4_original_IQ.txt",Nsamples);
    data.I = I4;
    data.Q = Q4;
    data.N = 512;
    data.sampleRate_Hz = sampleRate_Hz;
    TXInterpolateBy4(&data,&TXfilters);
    WriteIQFile(data.I,data.Q,"TXInterpolateBy4_interpolated_IQ_pass1.txt",2048);

    CreateIQTone(I4, Q4, Nsamples, sampleRate_Hz, tone_Hz);
    data.I = &I4[512];
    data.Q = &Q4[512];
    data.N = 512;
    data.sampleRate_Hz = sampleRate_Hz;
    TXInterpolateBy4(&data,&TXfilters);
    WriteIQFile(data.I,data.Q,"TXInterpolateBy4_interpolated_IQ_pass2.txt",2048);

    EXPECT_EQ(1,1);
}


TEST(TransmitChain, InterpolateByNPassband){
    uint32_t Nsamples = 128*2*2*4;
    uint32_t sampleRate_Hz = 192000/16;
    float I[Nsamples*2*4];
    float Q[Nsamples*2*4];
    float Iout[256*2*4];
    float Qout[256*2*4];
    DataBlock data;
    data.I = I;
    data.Q = Q;
    data.N = 128;
    data.sampleRate_Hz = sampleRate_Hz;

    float32_t fmin = 0.0;
    float32_t fmax = 48000.0;
    uint32_t Npoints = 101;
    float32_t fstep = (fmax - fmin)/(float32_t)Npoints;
    float32_t gainx4[Npoints];
    float32_t gainx2[Npoints];
    float32_t gainx2x2[Npoints];
    float32_t freq[Npoints];

    InitializeTransmitFilters(&TXfilters);

    float32_t amp;
    for (int i = 0; i<Npoints; i++){
        freq[i] = fmin + (float32_t)i*fstep;
        CreateIQTone(I, Q, Nsamples, sampleRate_Hz, freq[i]);
        data.I = I;
        data.Q = Q;
        TXInterpolateBy2Again(&data,&TXfilters);
        CreateIQTone(I, Q, Nsamples, sampleRate_Hz, freq[i]);
        data.I = &I[128];
        data.Q = &Q[128];
        TXInterpolateBy2Again(&data,&TXfilters);
        amp = getmax(data.I,256);
        gainx2x2[i] = amp/0.5;


        CreateIQTone(I, Q, Nsamples, sampleRate_Hz*2, freq[i]);
        data.I = I;
        data.Q = Q;
        TXInterpolateBy2(&data,&TXfilters);
        CreateIQTone(I, Q, Nsamples, sampleRate_Hz*2, freq[i]);
        data.I = &I[256];
        data.Q = &Q[256];
        TXInterpolateBy2(&data,&TXfilters);
        amp = getmax(data.I,512);
        gainx2[i] = amp/0.5;

        CreateIQTone(I, Q, Nsamples, sampleRate_Hz*2*4, freq[i]);
        data.I = I;
        data.Q = Q;
        data.N = 512;
        TXInterpolateBy4(&data,&TXfilters);

        CreateIQTone(I, Q, Nsamples, sampleRate_Hz*2*4, freq[i]);
        data.I = &I[512];
        data.Q = &Q[512];
        data.N = 512;
        TXInterpolateBy4(&data,&TXfilters);
        amp = getmax(data.I,2048);
        gainx4[i] = amp/0.5;

    }
    WriteIQFile(freq,gainx2x2,"TXInterpolateBy2x2_passband.txt",Npoints);
    WriteIQFile(freq,gainx2,"TXInterpolateBy2_passband.txt",Npoints);
    WriteIQFile(freq,gainx4,"TXInterpolateBy4_passband.txt",Npoints);
    EXPECT_EQ(1,1);
}

void end2end(float32_t *I, float32_t *Q){
    DataBlock data;
    data.I = I;
    data.Q = Q;
    data.N = 2048;
    data.sampleRate_Hz = 192000;
    TXDecimateBy4(&data,&TXfilters); // 2048 in, 512 out
    TXDecimateBy2(&data,&TXfilters);// 512 in, 256 out
    BandEQ(&data, &RXfilters, TX);
    arm_copy_f32(data.I,data.Q,256);
    TXDecimateBy2Again(&data,&TXfilters); // 256 in, 128 out
    HilbertTransform(&data,&TXfilters); // 128
    TXInterpolateBy2Again(&data,&TXfilters); // 128 in, 256 out
    ApplyIQCorrection(&data,
        ED.IQXAmpCorrectionFactor[ED.currentBand[ED.activeVFO]],
        ED.IQXPhaseCorrectionFactor[ED.currentBand[ED.activeVFO]]);
    SidebandSelection(&data);
    TXInterpolateBy2(&data,&TXfilters); // 256 in, 512 out
    TXInterpolateBy4(&data,&TXfilters); // 512 in, 2048 out
}

TEST(TransmitChain, EndToEnd){
    uint32_t Nsamples = 2048;
    uint32_t sampleRate_Hz = 192000;
    float I[Nsamples];
    float Q[Nsamples];
    int Nreps = 16;
    float IoutS[Nsamples*Nreps];
    float QoutS[Nsamples*Nreps];

    float32_t fmin = 0;
    float32_t fmax = 6000;
    uint32_t Npoints = 256;
    float32_t fstep = (fmax - fmin)/(float32_t)Npoints;
    float32_t gain[Npoints];
    float32_t freq[Npoints];
    float32_t sbs[Npoints];
    float32_t tone[Npoints];
    float32_t image[Npoints];
    InitializeTransmitFilters(&TXfilters);

    uint32_t spectrum_zoom = SPECTRUM_ZOOM_16;
    InitializeFilters(spectrum_zoom, &RXfilters);
    ZoomFFTPrep(spectrum_zoom, &RXfilters);
    DataBlock data;
    data.sampleRate_Hz = 192000;
    data.N = 2048;

    float32_t bandwidth = 192000 / 16;
    float32_t binwidth = bandwidth / 512;
    float32_t fcenter[512];
    float32_t fstart[512];
    float32_t fend[512];
    for (int i=0; i<512; i++){
        fcenter[i] = (float32_t)i*binwidth-bandwidth/2+binwidth/2;
        fstart[i] =  (float32_t)i*binwidth-bandwidth/2;
        fend[i] =    (float32_t)i*binwidth-bandwidth/2+binwidth;
    }
    bands[ED.currentBand[ED.activeVFO]].mode = LSB;
    float32_t amp;
    uint32_t phase = 0;
    for (int i = 0; i<Npoints; i++){
        freq[i] = fmin + (float32_t)i*fstep;

        for (int j=0; j<Nreps; j++){
            phase = CreateIQToneWithPhase(I,Q,2048,sampleRate_Hz,freq[i],phase,0.5);
            end2end(I, Q);
            arm_copy_f32(I,&IoutS[j*2048],2048);
            arm_copy_f32(Q,&QoutS[j*2048],2048);
            data.I = I;
            data.Q = Q;
            ZoomFFTExe(&data,spectrum_zoom,&RXfilters);
        }

        if (i==15){
            WriteIQFile(IoutS,QoutS,"TXEndToEnd_IQ_fixed.txt",2048*Nreps);
            WriteFile(psdnew,"TXEndToEnd_psd_fixed.txt",512);
        }
        // Calculate the sideband separation
        // What bin does this tone appear in?
        int j1;
        for (j1=0; j1<512; j1++){
            if ((freq[i]>=fstart[j1]) & (freq[i]<fend[j1])) break;
        }
        int j2 = 256-(j1-256);
        tone[i] = psdnew[j2]; 
        image[i] = psdnew[j1];
        sbs[i] = tone[i]-image[i];
        amp = getmax(data.I,2048);
        gain[i] = amp/0.5;
    }
    WriteIQFile(freq,gain,"TXEndToEnd_passband_fixed.txt",Npoints);
    WriteIQFile(freq,tone,"TXEndToEnd_tone_fixed.txt",Npoints);
    WriteIQFile(freq,image,"TXEndToEnd_image_fixed.txt",Npoints);
    WriteIQFile(freq,sbs,"TXEndToEnd_sidebandseparation_fixed.txt",Npoints);
    EXPECT_EQ(1,1);
}

TEST(TransmitChain, TwoTone){
    uint32_t Nsamples = 2048;
    uint32_t sampleRate_Hz = 192000;
    float I[Nsamples];
    float Q[Nsamples];
    int Nreps = 16;
    float IoutS[Nsamples*Nreps];
    float QoutS[Nsamples*Nreps];

    float32_t tone1_Hz = 700.0;
    float32_t tone2_Hz = 1900.0;

    InitializeTransmitFilters(&TXfilters);

    uint32_t spectrum_zoom = SPECTRUM_ZOOM_16;
    InitializeFilters(spectrum_zoom, &RXfilters);
    ZoomFFTPrep(spectrum_zoom, &RXfilters);

    uint32_t phase1 = 0;
    uint32_t phase2 = 0;
    bands[ED.currentBand[ED.activeVFO]].mode = LSB;
    for (int j=0; j<Nreps; j++){
        phase1 = CreateIQToneWithPhase(I,Q,2048,sampleRate_Hz,tone1_Hz,phase1,0.5);
        phase2 = AddIQToneWithPhase(I,Q,2048,sampleRate_Hz,tone2_Hz,phase2,0.5);
        end2end(I, Q);
        arm_copy_f32(I,&IoutS[j*2048],2048);
        arm_copy_f32(Q,&QoutS[j*2048],2048);
        // this does not have enough resolution because we're so damned oversampled
        CalcPSD512(&IoutS[j*2048],&QoutS[j*2048]);
    }

    WriteIQFile(IoutS,QoutS,"TXTwoTone_IQ.txt",2048*Nreps);
    WriteFile(psdnew,"TXTwoTone_psd.txt",512);
    EXPECT_EQ(1,1);
}

/**
 * Test that TransmitReceiveProcessing calculates the power spectrum during transmit.
 * This test verifies that the PSD (Power Spectral Density) is being calculated
 * when the TransmitReceiveProcessing function is called during SSB transmit mode.
 */
TEST(TransmitChain, TransmitReceiveProcessingCalculatesPSD){
    // Initialize the signal processing filters
    // TransmitReceiveProcessing uses RXTXfilters with spectrum_zoom = 3 (RXTXZoom is defined as 3 in DSP.cpp)
    InitializeFilters(3, &RXTXfilters);
    ZoomFFTPrep(3, &RXTXfilters);

    // Reset the PSD array to ensure we can detect when it's been updated
    ResetPSD();
    psdupdated = false;

    // Verify that psdnew starts at zero
    for (size_t i = 0; i < SPECTRUM_RES; i++){
        EXPECT_FLOAT_EQ(psdnew[i], 0.0);
    }

    // Set up the mock audio input queues with IQ data containing a known tone
    // Use the mock data channels (channel 0 = L_mock, channel 1 = R_mock)
    Q_in_L.setChannel(0);
    Q_in_R.setChannel(1);
    Q_in_L.clear();
    Q_in_R.clear();

    // Set the state machine to SSB_TRANSMIT state (TransmitReceiveProcessing is called in this state)
    modeSM.state_id = ModeSm_StateId_SSB_TRANSMIT;

    // Call TransmitReceiveProcessing multiple times to fill the zoom FFT ring buffer
    // With zoom=3, each call processes 2048/8=256 samples, and we need 512 samples total
    // So we need at least 2 calls to fill the buffer and trigger PSD calculation
    for (int i = 0; i < 3; i++) {
        TransmitReceiveProcessing();
    }

    // Verify that psdupdated flag is set, indicating PSD was calculated
    EXPECT_TRUE(psdupdated);

    // Verify that psdnew contains non-zero data (some bins should have signal power)
    // At minimum, we expect the array to have been written to
    bool hasNonZeroValues = false;
    for (size_t i = 0; i < SPECTRUM_RES; i++){
        if (psdnew[i] != 0.0){
            hasNonZeroValues = true;
            break;
        }
    }
    EXPECT_TRUE(hasNonZeroValues);

    // Write the PSD to a file for analysis
    WriteFile(psdnew, "TransmitReceiveProcessing_psd.txt", SPECTRUM_RES);
}

/**
 * Test that TransmitReceiveProcessing produces a PSD with a peak at the expected
 * frequency bin when given a known tone input.
 */
TEST(TransmitChain, TransmitReceiveProcessingPSDContainsCorrectTone){
    // Initialize the signal processing filters
    // TransmitReceiveProcessing uses RXTXfilters with spectrum_zoom = 3 (RXTXZoom is defined as 3 in DSP.cpp)
    InitializeFilters(3, &RXTXfilters);
    ZoomFFTPrep(3, &RXTXfilters);

    // Create IQ test data with a known tone at 6 kHz
    // With zoom=3, the FFT covers 24 kHz (decimated by 8), so we need a tone below Nyquist (12 kHz)
    uint32_t Nsamples = 2048 * 4; // Need enough samples to fill the mock buffer
    uint32_t sampleRate_Hz = 192000;
    float32_t tone_Hz = 6000.0; // Within the zoomed spectrum range
    static int16_t testI[2048*4];
    static int16_t testQ[2048*4];

    // Generate IQ tone and convert to int16 format for the mock queue
    float oneoverfs = 1.0f / (float)sampleRate_Hz;
    for (uint32_t i = 0; i < Nsamples; i++){
        float I = 0.5f * cos(TWO_PI * tone_Hz * (float)i * oneoverfs);
        float Q = 0.5f * sin(TWO_PI * tone_Hz * (float)i * oneoverfs);
        // Convert from float (-1 to +1) to int16
        testI[i] = (int16_t)(I * 32767.0f);
        testQ[i] = (int16_t)(Q * 32767.0f);
    }

    // Set up the mock audio input queues with our test data
    Q_in_L.setChannel(0, testI);
    Q_in_R.setChannel(1, testQ);
    Q_in_L.clear();
    Q_in_R.clear();

    // Reset the PSD array
    ResetPSD();
    psdupdated = false;

    // Set the state machine to SSB_TRANSMIT state
    modeSM.state_id = ModeSm_StateId_SSB_TRANSMIT;

    // Call TransmitReceiveProcessing multiple times to fill the zoom FFT ring buffer
    // With zoom=3, we need multiple calls to accumulate enough samples
    for (int i = 0; i < 3; i++) {
        TransmitReceiveProcessing();
    }

    // Verify that psdupdated flag is set
    EXPECT_TRUE(psdupdated);

    // Calculate the expected bin for our tone
    // For spectrum_zoom = 3, decimation by 8 gives effective sample rate of 24 kHz
    // The FFT is 512 points covering 24 kHz
    // Bin width = 24000 / 512 = 46.875 Hz
    // For 6 kHz tone: bin = 512/2 + 512*6000/24000 = 256 + 128 = 384
    int32_t expectedBin = frequency_to_bin(tone_Hz, 512, sampleRate_Hz / 8);

    // Find the peak in the PSD
    float32_t maxPsd = -1e10;
    int32_t maxBin = 0;
    for (int i = 0; i < SPECTRUM_RES; i++){
        if (psdnew[i] > maxPsd){
            maxPsd = psdnew[i];
            maxBin = i;
        }
    }

    // The peak should be at or very near the expected bin
    EXPECT_NEAR(maxBin, expectedBin, 2); // Allow 2 bins of tolerance

    // The peak should be significantly above the noise floor
    // Check that the peak is at least 10 dB above a nearby noise bin
    float32_t noiseLevel = psdnew[(expectedBin + 50) % SPECTRUM_RES];
    EXPECT_GT(maxPsd - noiseLevel, 1.0); // At least 10 dB difference (in log10 units, 1.0 = 10 dB)

    // Write the PSD to a file for analysis
    WriteFile(psdnew, "TransmitReceiveProcessing_tone_psd.txt", SPECTRUM_RES);
}

/**
 * Test that TransmitReceiveProcessing properly applies RF gain and IQ correction
 * before calculating the PSD.
 */
TEST(TransmitChain, TransmitReceiveProcessingAppliesGainAndCorrection){
    // Initialize the signal processing filters
    // TransmitReceiveProcessing uses RXTXfilters with spectrum_zoom = 3 (RXTXZoom is defined as 3 in DSP.cpp)
    InitializeFilters(3, &RXTXfilters);
    ZoomFFTPrep(3, &RXTXfilters);

    // Set up specific RF gain and IQ correction values
    float32_t originalRfGain = ED.rfGainAllBands_dB;
    float32_t originalBandGain = bands[ED.currentBand[ED.activeVFO]].RFgain_dB;
    float32_t originalAmpCorr = ED.IQAmpCorrectionFactor[ED.currentBand[ED.activeVFO]];
    float32_t originalPhsCorr = ED.IQPhaseCorrectionFactor[ED.currentBand[ED.activeVFO]];

    // Set test values - a moderate gain adjustment
    ED.rfGainAllBands_dB = 10.0; // 10 dB gain
    bands[ED.currentBand[ED.activeVFO]].RFgain_dB = 0.0;
    ED.IQAmpCorrectionFactor[ED.currentBand[ED.activeVFO]] = 1.0;
    ED.IQPhaseCorrectionFactor[ED.currentBand[ED.activeVFO]] = 0.0;

    // Set up mock data
    Q_in_L.setChannel(0);
    Q_in_R.setChannel(1);
    Q_in_L.clear();
    Q_in_R.clear();

    // Reset the PSD array
    ResetPSD();
    psdupdated = false;

    // Set the state machine to SSB_TRANSMIT state
    modeSM.state_id = ModeSm_StateId_SSB_TRANSMIT;

    // First measurement with +10 dB RF gain
    // Call multiple times to fill the zoom FFT ring buffer
    for (int i = 0; i < 3; i++) {
        TransmitReceiveProcessing();
    }
    float32_t psdWithGain[SPECTRUM_RES];
    for (size_t i = 0; i < SPECTRUM_RES; i++){
        psdWithGain[i] = psdnew[i];
    }

    // Reset and measure again with 0 dB RF gain
    Q_in_L.clear();
    Q_in_R.clear();
    ResetPSD();
    psdupdated = false;

    ED.rfGainAllBands_dB = 0.0; // 0 dB gain (no change)
    // Call multiple times to fill the zoom FFT ring buffer
    for (int i = 0; i < 3; i++) {
        TransmitReceiveProcessing();
    }

    // Find the peak bin in both measurements
    float32_t maxPsdWithGain = -1e10;
    float32_t maxPsdNoGain = -1e10;
    for (int i = 0; i < SPECTRUM_RES; i++){
        if (psdWithGain[i] > maxPsdWithGain) maxPsdWithGain = psdWithGain[i];
        if (psdnew[i] > maxPsdNoGain) maxPsdNoGain = psdnew[i];
    }

    // The measurement with +10 dB gain should have approximately 1.0 higher PSD
    // (since PSD is in log10 scale, 10 dB = 1.0 in log10 of power)
    // Note: This may not be exactly 1.0 due to the AGC-like behavior in CalcPSD512
    // but it should be noticeably higher
    EXPECT_GT(maxPsdWithGain, maxPsdNoGain);

    // Write results for analysis
    WriteFile(psdWithGain, "TransmitReceiveProcessing_withGain_psd.txt", SPECTRUM_RES);
    WriteFile(psdnew, "TransmitReceiveProcessing_noGain_psd.txt", SPECTRUM_RES);

    // Restore original values
    ED.rfGainAllBands_dB = originalRfGain;
    bands[ED.currentBand[ED.activeVFO]].RFgain_dB = originalBandGain;
    ED.IQAmpCorrectionFactor[ED.currentBand[ED.activeVFO]] = originalAmpCorr;
    ED.IQPhaseCorrectionFactor[ED.currentBand[ED.activeVFO]] = originalPhsCorr;
}

