/**
 * @file BuildInfo.h
 * @brief Build information automatically updated by git hooks
 *
 * This file is automatically generated by the post-commit git hook.
 * Do not edit manually - your changes will be overwritten.
 */

#ifndef BUILDINFO_H
#define BUILDINFO_H

#define GIT_COMMIT_HASH "8f9a5b4"
#define BUILD_TIMESTAMP "2026-02-07 07:18:04"

#endif // BUILDINFO_H
