// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var


typedef enum PowerCalSm_EventId
{
    PowerCalSm_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    PowerCalSm_EventId_AUTO = 1,
    PowerCalSm_EventId_CURVE_COMPLETE = 2,
    PowerCalSm_EventId_NEXT_POINT = 3,
    PowerCalSm_EventId_RECORD_DATA_POINT = 4,
    PowerCalSm_EventId_RESET = 5
} PowerCalSm_EventId;

enum
{
    PowerCalSm_EventIdCount = 6
};

typedef enum PowerCalSm_StateId
{
    PowerCalSm_StateId_ROOT = 0,
    PowerCalSm_StateId_ACQUISITION = 1,
    PowerCalSm_StateId_MEASUREMENTCOMPLETE = 2,
    PowerCalSm_StateId_POWERCOMPLETE = 3,
    PowerCalSm_StateId_POWERPOINT1 = 4,
    PowerCalSm_StateId_POWERPOINT2 = 5,
    PowerCalSm_StateId_POWERPOINT3 = 6,
    PowerCalSm_StateId_READ_AND_ADJUST = 7,
    PowerCalSm_StateId_SSBPOINT = 8
} PowerCalSm_StateId;

enum
{
    PowerCalSm_StateIdCount = 9
};


// Generated state machine
// forward declaration
typedef struct PowerCalSm PowerCalSm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct PowerCalSm_Vars
{
    uint32_t count_ms; // this var can be referenced in diagram
    uint32_t acquisitionDuration_ms;
} PowerCalSm_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void PowerCalSm_ctor(PowerCalSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void PowerCalSm_start(PowerCalSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void PowerCalSm_dispatch_event(PowerCalSm* sm, PowerCalSm_EventId event_id);

// Thread safe.
char const * PowerCalSm_state_id_to_string(PowerCalSm_StateId id);

// Thread safe.
char const * PowerCalSm_event_id_to_string(PowerCalSm_EventId id);

// Generated state machine
struct PowerCalSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    PowerCalSm_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    PowerCalSm_Vars vars;
};

