// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "PowerCalSm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
// #include "your_header_here.h"
// Forward declarations
#include <stdint.h> // for count var
typedef float float32_t;
void ResetPowerCalibration(void);
void StartPowerPoint(void);
void StartSSBPoint(void);
void RecordPowerDataPoint(void);
void CalculatePowerCurveFit(void);
void CalculateSSBPoint(void);
float32_t ReadSWR(void);
float32_t AdjustAttenuation(void);


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(PowerCalSm* sm, PowerCalSm_StateId desired_state);

static void ROOT_enter(PowerCalSm* sm);

static void ACQUISITION_enter(PowerCalSm* sm);

static void ACQUISITION_exit(PowerCalSm* sm);

static void ACQUISITION_do(PowerCalSm* sm);

static void MEASUREMENTCOMPLETE_enter(PowerCalSm* sm);

static void MEASUREMENTCOMPLETE_exit(PowerCalSm* sm);

static void MEASUREMENTCOMPLETE_reset(PowerCalSm* sm);

static void POWERCOMPLETE_enter(PowerCalSm* sm);

static void POWERCOMPLETE_exit(PowerCalSm* sm);

static void POWERCOMPLETE_curve_complete(PowerCalSm* sm);

static void POWERCOMPLETE_reset(PowerCalSm* sm);

static void POWERPOINT1_enter(PowerCalSm* sm);

static void POWERPOINT1_exit(PowerCalSm* sm);

static void POWERPOINT1_auto(PowerCalSm* sm);

static void POWERPOINT1_record_data_point(PowerCalSm* sm);

static void POWERPOINT2_enter(PowerCalSm* sm);

static void POWERPOINT2_exit(PowerCalSm* sm);

static void POWERPOINT2_record_data_point(PowerCalSm* sm);

static void POWERPOINT2_reset(PowerCalSm* sm);

static void POWERPOINT3_enter(PowerCalSm* sm);

static void POWERPOINT3_exit(PowerCalSm* sm);

static void POWERPOINT3_record_data_point(PowerCalSm* sm);

static void POWERPOINT3_reset(PowerCalSm* sm);

static void READ_AND_ADJUST_enter(PowerCalSm* sm);

static void READ_AND_ADJUST_exit(PowerCalSm* sm);

static void READ_AND_ADJUST_curve_complete(PowerCalSm* sm);

static void READ_AND_ADJUST_next_point(PowerCalSm* sm);

static void SSBPOINT_enter(PowerCalSm* sm);

static void SSBPOINT_exit(PowerCalSm* sm);

static void SSBPOINT_record_data_point(PowerCalSm* sm);

static void SSBPOINT_reset(PowerCalSm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void PowerCalSm_ctor(PowerCalSm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void PowerCalSm_start(PowerCalSm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(PowerPoint1)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `PowerPoint1`.
            POWERPOINT1_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void PowerCalSm_dispatch_event(PowerCalSm* sm, PowerCalSm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: PowerCalSm
        case PowerCalSm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: ACQUISITION
        case PowerCalSm_StateId_ACQUISITION:
            switch (event_id)
            {
                case PowerCalSm_EventId_DO: ACQUISITION_do(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: MeasurementComplete
        case PowerCalSm_StateId_MEASUREMENTCOMPLETE:
            switch (event_id)
            {
                case PowerCalSm_EventId_RESET: MEASUREMENTCOMPLETE_reset(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: PowerComplete
        case PowerCalSm_StateId_POWERCOMPLETE:
            switch (event_id)
            {
                case PowerCalSm_EventId_CURVE_COMPLETE: POWERCOMPLETE_curve_complete(sm); break;
                case PowerCalSm_EventId_RESET: POWERCOMPLETE_reset(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: PowerPoint1
        case PowerCalSm_StateId_POWERPOINT1:
            switch (event_id)
            {
                case PowerCalSm_EventId_RECORD_DATA_POINT: POWERPOINT1_record_data_point(sm); break;
                case PowerCalSm_EventId_AUTO: POWERPOINT1_auto(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: PowerPoint2
        case PowerCalSm_StateId_POWERPOINT2:
            switch (event_id)
            {
                case PowerCalSm_EventId_RECORD_DATA_POINT: POWERPOINT2_record_data_point(sm); break;
                case PowerCalSm_EventId_RESET: POWERPOINT2_reset(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: PowerPoint3
        case PowerCalSm_StateId_POWERPOINT3:
            switch (event_id)
            {
                case PowerCalSm_EventId_RECORD_DATA_POINT: POWERPOINT3_record_data_point(sm); break;
                case PowerCalSm_EventId_RESET: POWERPOINT3_reset(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: READ_AND_ADJUST
        case PowerCalSm_StateId_READ_AND_ADJUST:
            switch (event_id)
            {
                case PowerCalSm_EventId_NEXT_POINT: READ_AND_ADJUST_next_point(sm); break;
                case PowerCalSm_EventId_CURVE_COMPLETE: READ_AND_ADJUST_curve_complete(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: SSBPoint
        case PowerCalSm_StateId_SSBPOINT:
            switch (event_id)
            {
                case PowerCalSm_EventId_RECORD_DATA_POINT: SSBPOINT_record_data_point(sm); break;
                case PowerCalSm_EventId_RESET: SSBPOINT_reset(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(PowerCalSm* sm, PowerCalSm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case PowerCalSm_StateId_ACQUISITION: ACQUISITION_exit(sm); break;
            
            case PowerCalSm_StateId_MEASUREMENTCOMPLETE: MEASUREMENTCOMPLETE_exit(sm); break;
            
            case PowerCalSm_StateId_POWERCOMPLETE: POWERCOMPLETE_exit(sm); break;
            
            case PowerCalSm_StateId_POWERPOINT1: POWERPOINT1_exit(sm); break;
            
            case PowerCalSm_StateId_POWERPOINT2: POWERPOINT2_exit(sm); break;
            
            case PowerCalSm_StateId_POWERPOINT3: POWERPOINT3_exit(sm); break;
            
            case PowerCalSm_StateId_READ_AND_ADJUST: READ_AND_ADJUST_exit(sm); break;
            
            case PowerCalSm_StateId_SSBPOINT: SSBPOINT_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ACQUISITION
////////////////////////////////////////////////////////////////////////////////

static void ACQUISITION_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_ACQUISITION;
    
    // ACQUISITION behavior
    // uml: enter / { count_ms = 0; }
    {
        // Step 1: execute action `count_ms = 0;`
        sm->vars.count_ms = 0; 
    } // end of behavior for ACQUISITION
}

static void ACQUISITION_exit(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_ROOT;
}

static void ACQUISITION_do(PowerCalSm* sm)
{
    // ACQUISITION behavior
    // uml: 1. do / { count_ms++; }
    {
        // Step 1: execute action `count_ms++;`
        sm->vars.count_ms++;
    } // end of behavior for ACQUISITION
    
    // ACQUISITION behavior
    // uml: do [count_ms >= acquisitionDuration_ms] TransitionTo(READ_AND_ADJUST)
    if (sm->vars.count_ms >= sm->vars.acquisitionDuration_ms)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ACQUISITION_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `READ_AND_ADJUST`.
        READ_AND_ADJUST_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ACQUISITION
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MEASUREMENTCOMPLETE
////////////////////////////////////////////////////////////////////////////////

static void MEASUREMENTCOMPLETE_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_MEASUREMENTCOMPLETE;
    
    // MeasurementComplete behavior
    // uml: enter / { CalculateSSBPoint(); }
    {
        // Step 1: execute action `CalculateSSBPoint();`
        CalculateSSBPoint();
    } // end of behavior for MeasurementComplete
}

static void MEASUREMENTCOMPLETE_exit(PowerCalSm* sm)
{
    // MeasurementComplete behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for MeasurementComplete
    
    sm->state_id = PowerCalSm_StateId_ROOT;
}

static void MEASUREMENTCOMPLETE_reset(PowerCalSm* sm)
{
    // MeasurementComplete behavior
    // uml: RESET TransitionTo(PowerPoint1)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        MEASUREMENTCOMPLETE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PowerPoint1`.
        POWERPOINT1_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for MeasurementComplete
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state POWERCOMPLETE
////////////////////////////////////////////////////////////////////////////////

static void POWERCOMPLETE_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_POWERCOMPLETE;
    
    // PowerComplete behavior
    // uml: enter / { CalculatePowerCurveFit(); }
    {
        // Step 1: execute action `CalculatePowerCurveFit();`
        CalculatePowerCurveFit();
    } // end of behavior for PowerComplete
}

static void POWERCOMPLETE_exit(PowerCalSm* sm)
{
    // PowerComplete behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for PowerComplete
    
    sm->state_id = PowerCalSm_StateId_ROOT;
}

static void POWERCOMPLETE_curve_complete(PowerCalSm* sm)
{
    // PowerComplete behavior
    // uml: CURVE_COMPLETE TransitionTo(SSBPoint)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        POWERCOMPLETE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `SSBPoint`.
        SSBPOINT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PowerComplete
    
    // No ancestor handles this event.
}

static void POWERCOMPLETE_reset(PowerCalSm* sm)
{
    // PowerComplete behavior
    // uml: RESET TransitionTo(PowerPoint1)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        POWERCOMPLETE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PowerPoint1`.
        POWERPOINT1_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PowerComplete
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state POWERPOINT1
////////////////////////////////////////////////////////////////////////////////

static void POWERPOINT1_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_POWERPOINT1;
    
    // PowerPoint1 behavior
    // uml: enter / { ResetPowerCalibration(); }
    {
        // Step 1: execute action `ResetPowerCalibration();`
        ResetPowerCalibration();
    } // end of behavior for PowerPoint1
}

static void POWERPOINT1_exit(PowerCalSm* sm)
{
    // PowerPoint1 behavior
    // uml: exit / { RecordPowerDataPoint(); }
    {
        // Step 1: execute action `RecordPowerDataPoint();`
        RecordPowerDataPoint();
    } // end of behavior for PowerPoint1
    
    sm->state_id = PowerCalSm_StateId_ROOT;
}

static void POWERPOINT1_auto(PowerCalSm* sm)
{
    // PowerPoint1 behavior
    // uml: AUTO TransitionTo(ACQUISITION)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        POWERPOINT1_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ACQUISITION`.
        ACQUISITION_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PowerPoint1
    
    // No ancestor handles this event.
}

static void POWERPOINT1_record_data_point(PowerCalSm* sm)
{
    // PowerPoint1 behavior
    // uml: RECORD_DATA_POINT TransitionTo(PowerPoint2)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        POWERPOINT1_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PowerPoint2`.
        POWERPOINT2_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PowerPoint1
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state POWERPOINT2
////////////////////////////////////////////////////////////////////////////////

static void POWERPOINT2_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_POWERPOINT2;
    
    // PowerPoint2 behavior
    // uml: enter / { StartPowerPoint(); }
    {
        // Step 1: execute action `StartPowerPoint();`
        StartPowerPoint(); 
    } // end of behavior for PowerPoint2
}

static void POWERPOINT2_exit(PowerCalSm* sm)
{
    // PowerPoint2 behavior
    // uml: exit / { RecordPowerDataPoint(); }
    {
        // Step 1: execute action `RecordPowerDataPoint();`
        RecordPowerDataPoint();
    } // end of behavior for PowerPoint2
    
    sm->state_id = PowerCalSm_StateId_ROOT;
}

static void POWERPOINT2_record_data_point(PowerCalSm* sm)
{
    // PowerPoint2 behavior
    // uml: RECORD_DATA_POINT TransitionTo(PowerPoint3)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        POWERPOINT2_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PowerPoint3`.
        POWERPOINT3_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PowerPoint2
    
    // No ancestor handles this event.
}

static void POWERPOINT2_reset(PowerCalSm* sm)
{
    // PowerPoint2 behavior
    // uml: RESET TransitionTo(PowerPoint1)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        POWERPOINT2_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PowerPoint1`.
        POWERPOINT1_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PowerPoint2
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state POWERPOINT3
////////////////////////////////////////////////////////////////////////////////

static void POWERPOINT3_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_POWERPOINT3;
    
    // PowerPoint3 behavior
    // uml: enter / { StartPowerPoint(); }
    {
        // Step 1: execute action `StartPowerPoint();`
        StartPowerPoint();
    } // end of behavior for PowerPoint3
}

static void POWERPOINT3_exit(PowerCalSm* sm)
{
    // PowerPoint3 behavior
    // uml: exit / { RecordPowerDataPoint(); }
    {
        // Step 1: execute action `RecordPowerDataPoint();`
        RecordPowerDataPoint();
    } // end of behavior for PowerPoint3
    
    sm->state_id = PowerCalSm_StateId_ROOT;
}

static void POWERPOINT3_record_data_point(PowerCalSm* sm)
{
    // PowerPoint3 behavior
    // uml: RECORD_DATA_POINT TransitionTo(PowerComplete)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        POWERPOINT3_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PowerComplete`.
        POWERCOMPLETE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PowerPoint3
    
    // No ancestor handles this event.
}

static void POWERPOINT3_reset(PowerCalSm* sm)
{
    // PowerPoint3 behavior
    // uml: RESET TransitionTo(PowerPoint1)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        POWERPOINT3_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PowerPoint1`.
        POWERPOINT1_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for PowerPoint3
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state READ_AND_ADJUST
////////////////////////////////////////////////////////////////////////////////

static void READ_AND_ADJUST_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_READ_AND_ADJUST;
    
    // READ_AND_ADJUST behavior
    // uml: enter / { AdjustAttenuation(); }
    {
        // Step 1: execute action `AdjustAttenuation();`
        AdjustAttenuation();
    } // end of behavior for READ_AND_ADJUST
}

static void READ_AND_ADJUST_exit(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_ROOT;
}

static void READ_AND_ADJUST_curve_complete(PowerCalSm* sm)
{
    // READ_AND_ADJUST behavior
    // uml: CURVE_COMPLETE TransitionTo(SSBPoint)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        READ_AND_ADJUST_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `SSBPoint`.
        SSBPOINT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for READ_AND_ADJUST
    
    // No ancestor handles this event.
}

static void READ_AND_ADJUST_next_point(PowerCalSm* sm)
{
    // READ_AND_ADJUST behavior
    // uml: NEXT_POINT TransitionTo(ACQUISITION)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        READ_AND_ADJUST_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ACQUISITION`.
        ACQUISITION_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for READ_AND_ADJUST
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SSBPOINT
////////////////////////////////////////////////////////////////////////////////

static void SSBPOINT_enter(PowerCalSm* sm)
{
    sm->state_id = PowerCalSm_StateId_SSBPOINT;
    
    // SSBPoint behavior
    // uml: enter / { StartSSBPoint(); }
    {
        // Step 1: execute action `StartSSBPoint();`
        StartSSBPoint();
    } // end of behavior for SSBPoint
}

static void SSBPOINT_exit(PowerCalSm* sm)
{
    // SSBPoint behavior
    // uml: exit / { RecordPowerDataPoint(); }
    {
        // Step 1: execute action `RecordPowerDataPoint();`
        RecordPowerDataPoint();
    } // end of behavior for SSBPoint
    
    sm->state_id = PowerCalSm_StateId_ROOT;
}

static void SSBPOINT_record_data_point(PowerCalSm* sm)
{
    // SSBPoint behavior
    // uml: RECORD_DATA_POINT TransitionTo(MeasurementComplete)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        SSBPOINT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `MeasurementComplete`.
        MEASUREMENTCOMPLETE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for SSBPoint
    
    // No ancestor handles this event.
}

static void SSBPOINT_reset(PowerCalSm* sm)
{
    // SSBPoint behavior
    // uml: RESET TransitionTo(PowerPoint1)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        SSBPOINT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `PowerPoint1`.
        POWERPOINT1_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for SSBPoint
    
    // No ancestor handles this event.
}

// Thread safe.
char const * PowerCalSm_state_id_to_string(PowerCalSm_StateId id)
{
    switch (id)
    {
        case PowerCalSm_StateId_ROOT: return "ROOT";
        case PowerCalSm_StateId_ACQUISITION: return "ACQUISITION";
        case PowerCalSm_StateId_MEASUREMENTCOMPLETE: return "MEASUREMENTCOMPLETE";
        case PowerCalSm_StateId_POWERCOMPLETE: return "POWERCOMPLETE";
        case PowerCalSm_StateId_POWERPOINT1: return "POWERPOINT1";
        case PowerCalSm_StateId_POWERPOINT2: return "POWERPOINT2";
        case PowerCalSm_StateId_POWERPOINT3: return "POWERPOINT3";
        case PowerCalSm_StateId_READ_AND_ADJUST: return "READ_AND_ADJUST";
        case PowerCalSm_StateId_SSBPOINT: return "SSBPOINT";
        default: return "?";
    }
}

// Thread safe.
char const * PowerCalSm_event_id_to_string(PowerCalSm_EventId id)
{
    switch (id)
    {
        case PowerCalSm_EventId_AUTO: return "AUTO";
        case PowerCalSm_EventId_CURVE_COMPLETE: return "CURVE_COMPLETE";
        case PowerCalSm_EventId_DO: return "DO";
        case PowerCalSm_EventId_NEXT_POINT: return "NEXT_POINT";
        case PowerCalSm_EventId_RECORD_DATA_POINT: return "RECORD_DATA_POINT";
        case PowerCalSm_EventId_RESET: return "RESET";
        default: return "?";
    }
}
