// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var


typedef enum ReceiveIQCalSm_EventId
{
    ReceiveIQCalSm_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    ReceiveIQCalSm_EventId_AUTO = 1,
    ReceiveIQCalSm_EventId_AUTO_COMPLETE = 2,
    ReceiveIQCalSm_EventId_FIND_MINIMUM = 3,
    ReceiveIQCalSm_EventId_MIN_EXIT = 4,
    ReceiveIQCalSm_EventId_NEXT_POINT = 5,
    ReceiveIQCalSm_EventId_READ_DELTA = 6
} ReceiveIQCalSm_EventId;

enum
{
    ReceiveIQCalSm_EventIdCount = 7
};

typedef enum ReceiveIQCalSm_StateId
{
    ReceiveIQCalSm_StateId_ROOT = 0,
    ReceiveIQCalSm_StateId_BAND_ADJUST = 1,
    ReceiveIQCalSm_StateId_FIND_MINIMUM = 2,
    ReceiveIQCalSm_StateId_ADJUST = 3,
    ReceiveIQCalSm_StateId_READ = 4,
    ReceiveIQCalSm_StateId_WAIT = 5,
    ReceiveIQCalSm_StateId_STANDBY = 6
} ReceiveIQCalSm_StateId;

enum
{
    ReceiveIQCalSm_StateIdCount = 7
};


// Generated state machine
// forward declaration
typedef struct ReceiveIQCalSm ReceiveIQCalSm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct ReceiveIQCalSm_Vars
{
    uint32_t count_ms; // this var can be referenced in diagram
    uint32_t acquisitionDuration_ms;
} ReceiveIQCalSm_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void ReceiveIQCalSm_ctor(ReceiveIQCalSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void ReceiveIQCalSm_start(ReceiveIQCalSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void ReceiveIQCalSm_dispatch_event(ReceiveIQCalSm* sm, ReceiveIQCalSm_EventId event_id);

// Thread safe.
char const * ReceiveIQCalSm_state_id_to_string(ReceiveIQCalSm_StateId id);

// Thread safe.
char const * ReceiveIQCalSm_event_id_to_string(ReceiveIQCalSm_EventId id);

// Generated state machine
struct ReceiveIQCalSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    ReceiveIQCalSm_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    ReceiveIQCalSm_Vars vars;
};

