// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var


typedef enum TransmitIQCalSm_EventId
{
    TransmitIQCalSm_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    TransmitIQCalSm_EventId_AUTO = 1,
    TransmitIQCalSm_EventId_AUTO_COMPLETE = 2,
    TransmitIQCalSm_EventId_FIND_MINIMUM = 3,
    TransmitIQCalSm_EventId_MIN_EXIT = 4,
    TransmitIQCalSm_EventId_NEXT_POINT = 5,
    TransmitIQCalSm_EventId_READ_DELTA = 6
} TransmitIQCalSm_EventId;

enum
{
    TransmitIQCalSm_EventIdCount = 7
};

typedef enum TransmitIQCalSm_StateId
{
    TransmitIQCalSm_StateId_ROOT = 0,
    TransmitIQCalSm_StateId_BAND_ADJUST = 1,
    TransmitIQCalSm_StateId_FIND_MINIMUM = 2,
    TransmitIQCalSm_StateId_ADJUST = 3,
    TransmitIQCalSm_StateId_READ = 4,
    TransmitIQCalSm_StateId_WAIT = 5,
    TransmitIQCalSm_StateId_STANDBY = 6
} TransmitIQCalSm_StateId;

enum
{
    TransmitIQCalSm_StateIdCount = 7
};


// Generated state machine
// forward declaration
typedef struct TransmitIQCalSm TransmitIQCalSm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct TransmitIQCalSm_Vars
{
    uint32_t count_ms; // this var can be referenced in diagram
    uint32_t acquisitionDuration_ms;
} TransmitIQCalSm_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TransmitIQCalSm_ctor(TransmitIQCalSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TransmitIQCalSm_start(TransmitIQCalSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TransmitIQCalSm_dispatch_event(TransmitIQCalSm* sm, TransmitIQCalSm_EventId event_id);

// Thread safe.
char const * TransmitIQCalSm_state_id_to_string(TransmitIQCalSm_StateId id);

// Thread safe.
char const * TransmitIQCalSm_event_id_to_string(TransmitIQCalSm_EventId id);

// Generated state machine
struct TransmitIQCalSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    TransmitIQCalSm_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    TransmitIQCalSm_Vars vars;
};

