// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for count var


typedef enum TransmitCarrierCalSm_EventId
{
    TransmitCarrierCalSm_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    TransmitCarrierCalSm_EventId_AUTO = 1,
    TransmitCarrierCalSm_EventId_AUTO_COMPLETE = 2,
    TransmitCarrierCalSm_EventId_FIND_MINIMUM = 3,
    TransmitCarrierCalSm_EventId_MIN_EXIT = 4,
    TransmitCarrierCalSm_EventId_NEXT_POINT = 5,
    TransmitCarrierCalSm_EventId_READ_DELTA = 6
} TransmitCarrierCalSm_EventId;

enum
{
    TransmitCarrierCalSm_EventIdCount = 7
};

typedef enum TransmitCarrierCalSm_StateId
{
    TransmitCarrierCalSm_StateId_ROOT = 0,
    TransmitCarrierCalSm_StateId_BAND_ADJUST = 1,
    TransmitCarrierCalSm_StateId_FIND_MINIMUM = 2,
    TransmitCarrierCalSm_StateId_ADJUST = 3,
    TransmitCarrierCalSm_StateId_READ = 4,
    TransmitCarrierCalSm_StateId_WAIT = 5,
    TransmitCarrierCalSm_StateId_STANDBY = 6
} TransmitCarrierCalSm_StateId;

enum
{
    TransmitCarrierCalSm_StateIdCount = 7
};


// Generated state machine
// forward declaration
typedef struct TransmitCarrierCalSm TransmitCarrierCalSm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct TransmitCarrierCalSm_Vars
{
    uint32_t count_ms; // this var can be referenced in diagram
    uint32_t acquisitionDuration_ms;
} TransmitCarrierCalSm_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TransmitCarrierCalSm_ctor(TransmitCarrierCalSm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TransmitCarrierCalSm_start(TransmitCarrierCalSm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TransmitCarrierCalSm_dispatch_event(TransmitCarrierCalSm* sm, TransmitCarrierCalSm_EventId event_id);

// Thread safe.
char const * TransmitCarrierCalSm_state_id_to_string(TransmitCarrierCalSm_StateId id);

// Thread safe.
char const * TransmitCarrierCalSm_event_id_to_string(TransmitCarrierCalSm_EventId id);

// Generated state machine
struct TransmitCarrierCalSm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    TransmitCarrierCalSm_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    TransmitCarrierCalSm_Vars vars;
};

