// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "TransmitCarrierCalSm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
// #include "your_header_here.h"
// Forward declarations
#include <stdint.h> // for count var
void ResetTXCarrierCalBand(void);
void AdjustTXCarrierBand(void);
void ResetTXCarrierCalSettings(void);
void UpdateTXDeltaVal(void);
void AdjustTXCarrierCalSetting(void);
void ReadTXCarrierDelta(void);


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TransmitCarrierCalSm* sm, TransmitCarrierCalSm_StateId desired_state);

static void ROOT_enter(TransmitCarrierCalSm* sm);

static void BAND_ADJUST_enter(TransmitCarrierCalSm* sm);

static void BAND_ADJUST_exit(TransmitCarrierCalSm* sm);

static void BAND_ADJUST_auto_complete(TransmitCarrierCalSm* sm);

static void BAND_ADJUST_find_minimum(TransmitCarrierCalSm* sm);

static void FIND_MINIMUM_enter(TransmitCarrierCalSm* sm);

static void FIND_MINIMUM_exit(TransmitCarrierCalSm* sm);

static void FIND_MINIMUM_do(TransmitCarrierCalSm* sm);

static void FIND_MINIMUM_ExitPoint_done__transition(TransmitCarrierCalSm* sm);

static void ADJUST_enter(TransmitCarrierCalSm* sm);

static void ADJUST_exit(TransmitCarrierCalSm* sm);

static void ADJUST_min_exit(TransmitCarrierCalSm* sm);

static void ADJUST_read_delta(TransmitCarrierCalSm* sm);

static void READ_enter(TransmitCarrierCalSm* sm);

static void READ_exit(TransmitCarrierCalSm* sm);

static void READ_min_exit(TransmitCarrierCalSm* sm);

static void READ_next_point(TransmitCarrierCalSm* sm);

static void WAIT_enter(TransmitCarrierCalSm* sm);

static void WAIT_exit(TransmitCarrierCalSm* sm);

static void WAIT_do(TransmitCarrierCalSm* sm);

static void STANDBY_enter(TransmitCarrierCalSm* sm);

static void STANDBY_exit(TransmitCarrierCalSm* sm);

static void STANDBY_auto(TransmitCarrierCalSm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TransmitCarrierCalSm_ctor(TransmitCarrierCalSm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TransmitCarrierCalSm_start(TransmitCarrierCalSm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(STANDBY)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `STANDBY`.
            STANDBY_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TransmitCarrierCalSm_dispatch_event(TransmitCarrierCalSm* sm, TransmitCarrierCalSm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: TransmitCarrierCalSm
        case TransmitCarrierCalSm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: BAND_ADJUST
        case TransmitCarrierCalSm_StateId_BAND_ADJUST:
            switch (event_id)
            {
                case TransmitCarrierCalSm_EventId_FIND_MINIMUM: BAND_ADJUST_find_minimum(sm); break;
                case TransmitCarrierCalSm_EventId_AUTO_COMPLETE: BAND_ADJUST_auto_complete(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: FIND_MINIMUM
        case TransmitCarrierCalSm_StateId_FIND_MINIMUM:
            switch (event_id)
            {
                case TransmitCarrierCalSm_EventId_DO: FIND_MINIMUM_do(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: ADJUST
        case TransmitCarrierCalSm_StateId_ADJUST:
            switch (event_id)
            {
                case TransmitCarrierCalSm_EventId_MIN_EXIT: ADJUST_min_exit(sm); break;
                case TransmitCarrierCalSm_EventId_READ_DELTA: ADJUST_read_delta(sm); break;
                case TransmitCarrierCalSm_EventId_DO: FIND_MINIMUM_do(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: READ
        case TransmitCarrierCalSm_StateId_READ:
            switch (event_id)
            {
                case TransmitCarrierCalSm_EventId_NEXT_POINT: READ_next_point(sm); break;
                case TransmitCarrierCalSm_EventId_MIN_EXIT: READ_min_exit(sm); break;
                case TransmitCarrierCalSm_EventId_DO: FIND_MINIMUM_do(sm); break; // First ancestor handler for this event
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: WAIT
        case TransmitCarrierCalSm_StateId_WAIT:
            switch (event_id)
            {
                case TransmitCarrierCalSm_EventId_DO: WAIT_do(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: STANDBY
        case TransmitCarrierCalSm_StateId_STANDBY:
            switch (event_id)
            {
                case TransmitCarrierCalSm_EventId_AUTO: STANDBY_auto(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TransmitCarrierCalSm* sm, TransmitCarrierCalSm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case TransmitCarrierCalSm_StateId_BAND_ADJUST: BAND_ADJUST_exit(sm); break;
            
            case TransmitCarrierCalSm_StateId_FIND_MINIMUM: FIND_MINIMUM_exit(sm); break;
            
            case TransmitCarrierCalSm_StateId_ADJUST: ADJUST_exit(sm); break;
            
            case TransmitCarrierCalSm_StateId_READ: READ_exit(sm); break;
            
            case TransmitCarrierCalSm_StateId_WAIT: WAIT_exit(sm); break;
            
            case TransmitCarrierCalSm_StateId_STANDBY: STANDBY_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state BAND_ADJUST
////////////////////////////////////////////////////////////////////////////////

static void BAND_ADJUST_enter(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_BAND_ADJUST;
    
    // BAND_ADJUST behavior
    // uml: enter / { AdjustTXCarrierBand(); }
    {
        // Step 1: execute action `AdjustTXCarrierBand();`
        AdjustTXCarrierBand();
    } // end of behavior for BAND_ADJUST
}

static void BAND_ADJUST_exit(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_ROOT;
}

static void BAND_ADJUST_auto_complete(TransmitCarrierCalSm* sm)
{
    // BAND_ADJUST behavior
    // uml: AUTO_COMPLETE TransitionTo(STANDBY)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        BAND_ADJUST_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `STANDBY`.
        STANDBY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for BAND_ADJUST
    
    // No ancestor handles this event.
}

static void BAND_ADJUST_find_minimum(TransmitCarrierCalSm* sm)
{
    // BAND_ADJUST behavior
    // uml: FIND_MINIMUM TransitionTo(FIND_MINIMUM)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        BAND_ADJUST_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `FIND_MINIMUM`.
        FIND_MINIMUM_enter(sm);
        
        // FIND_MINIMUM.<InitialState> behavior
        // uml: TransitionTo(ADJUST)
        {
            // Step 1: Exit states until we reach `FIND_MINIMUM` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `ADJUST`.
            ADJUST_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for FIND_MINIMUM.<InitialState>
    } // end of behavior for BAND_ADJUST
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FIND_MINIMUM
////////////////////////////////////////////////////////////////////////////////

static void FIND_MINIMUM_enter(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_FIND_MINIMUM;
    
    // FIND_MINIMUM behavior
    // uml: enter / { ResetTXCarrierCalSettings(); }
    {
        // Step 1: execute action `ResetTXCarrierCalSettings();`
        ResetTXCarrierCalSettings();
    } // end of behavior for FIND_MINIMUM
}

static void FIND_MINIMUM_exit(TransmitCarrierCalSm* sm)
{
    // FIND_MINIMUM behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for FIND_MINIMUM
    
    sm->state_id = TransmitCarrierCalSm_StateId_ROOT;
}

static void FIND_MINIMUM_do(TransmitCarrierCalSm* sm)
{
    // FIND_MINIMUM behavior
    // uml: do
    {
        // Step 1: execute action ``
    } // end of behavior for FIND_MINIMUM
    
    // No ancestor handles this event.
}

static void FIND_MINIMUM_ExitPoint_done__transition(TransmitCarrierCalSm* sm)
{
    // FIND_MINIMUM.<ExitPoint>(done) behavior
    // uml: TransitionTo(BAND_ADJUST)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        FIND_MINIMUM_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `BAND_ADJUST`.
        BAND_ADJUST_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FIND_MINIMUM.<ExitPoint>(done)
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ADJUST
////////////////////////////////////////////////////////////////////////////////

static void ADJUST_enter(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_ADJUST;
    
    // ADJUST behavior
    // uml: enter / { AdjustTXCarrierCalSetting(); }
    {
        // Step 1: execute action `AdjustTXCarrierCalSetting();`
        AdjustTXCarrierCalSetting();
    } // end of behavior for ADJUST
}

static void ADJUST_exit(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_FIND_MINIMUM;
}

static void ADJUST_min_exit(TransmitCarrierCalSm* sm)
{
    // ADJUST behavior
    // uml: MIN_EXIT TransitionTo(FIND_MINIMUM.<ExitPoint>(done))
    {
        // Step 1: Exit states until we reach `FIND_MINIMUM` state (Least Common Ancestor for transition).
        ADJUST_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `FIND_MINIMUM.<ExitPoint>(done)`.
        // FIND_MINIMUM.<ExitPoint>(done) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        FIND_MINIMUM_ExitPoint_done__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for ADJUST
    
    // No ancestor handles this event.
}

static void ADJUST_read_delta(TransmitCarrierCalSm* sm)
{
    // ADJUST behavior
    // uml: READ_DELTA TransitionTo(WAIT)
    {
        // Step 1: Exit states until we reach `FIND_MINIMUM` state (Least Common Ancestor for transition).
        ADJUST_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `WAIT`.
        WAIT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for ADJUST
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state READ
////////////////////////////////////////////////////////////////////////////////

static void READ_enter(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_READ;
    
    // READ behavior
    // uml: enter / { ReadTXCarrierDelta(); }
    {
        // Step 1: execute action `ReadTXCarrierDelta();`
        ReadTXCarrierDelta();
    } // end of behavior for READ
}

static void READ_exit(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_FIND_MINIMUM;
}

static void READ_min_exit(TransmitCarrierCalSm* sm)
{
    // READ behavior
    // uml: MIN_EXIT TransitionTo(FIND_MINIMUM.<ExitPoint>(done))
    {
        // Step 1: Exit states until we reach `FIND_MINIMUM` state (Least Common Ancestor for transition).
        READ_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `FIND_MINIMUM.<ExitPoint>(done)`.
        // FIND_MINIMUM.<ExitPoint>(done) is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        FIND_MINIMUM_ExitPoint_done__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for READ
    
    // No ancestor handles this event.
}

static void READ_next_point(TransmitCarrierCalSm* sm)
{
    // READ behavior
    // uml: NEXT_POINT TransitionTo(ADJUST)
    {
        // Step 1: Exit states until we reach `FIND_MINIMUM` state (Least Common Ancestor for transition).
        READ_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ADJUST`.
        ADJUST_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for READ
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state WAIT
////////////////////////////////////////////////////////////////////////////////

static void WAIT_enter(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_WAIT;
    
    // WAIT behavior
    // uml: enter / { count_ms = 0; }
    {
        // Step 1: execute action `count_ms = 0;`
        sm->vars.count_ms = 0; 
    } // end of behavior for WAIT
}

static void WAIT_exit(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_FIND_MINIMUM;
}

static void WAIT_do(TransmitCarrierCalSm* sm)
{
    bool consume_event = false;
    
    // WAIT behavior
    // uml: do / { count_ms++; }
    {
        // `do` events are not normally consumed.
        // Step 1: execute action `count_ms++;`
        sm->vars.count_ms++;
    } // end of behavior for WAIT
    
    // WAIT behavior
    // uml: do [count_ms >= acquisitionDuration_ms] TransitionTo(READ)
    if (sm->vars.count_ms >= sm->vars.acquisitionDuration_ms)
    {
        // Step 1: Exit states until we reach `FIND_MINIMUM` state (Least Common Ancestor for transition).
        WAIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `READ`.
        READ_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for WAIT
    
    // Check if event has been consumed before calling ancestor handler.
    if (!consume_event)
    {
        FIND_MINIMUM_do(sm);
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STANDBY
////////////////////////////////////////////////////////////////////////////////

static void STANDBY_enter(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_STANDBY;
    
    // STANDBY behavior
    // uml: enter / { ResetTXCarrierCalBand(); }
    {
        // Step 1: execute action `ResetTXCarrierCalBand();`
        ResetTXCarrierCalBand();
    } // end of behavior for STANDBY
}

static void STANDBY_exit(TransmitCarrierCalSm* sm)
{
    sm->state_id = TransmitCarrierCalSm_StateId_ROOT;
}

static void STANDBY_auto(TransmitCarrierCalSm* sm)
{
    // STANDBY behavior
    // uml: AUTO TransitionTo(BAND_ADJUST)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        STANDBY_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `BAND_ADJUST`.
        BAND_ADJUST_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for STANDBY
    
    // No ancestor handles this event.
}

// Thread safe.
char const * TransmitCarrierCalSm_state_id_to_string(TransmitCarrierCalSm_StateId id)
{
    switch (id)
    {
        case TransmitCarrierCalSm_StateId_ROOT: return "ROOT";
        case TransmitCarrierCalSm_StateId_BAND_ADJUST: return "BAND_ADJUST";
        case TransmitCarrierCalSm_StateId_FIND_MINIMUM: return "FIND_MINIMUM";
        case TransmitCarrierCalSm_StateId_ADJUST: return "ADJUST";
        case TransmitCarrierCalSm_StateId_READ: return "READ";
        case TransmitCarrierCalSm_StateId_WAIT: return "WAIT";
        case TransmitCarrierCalSm_StateId_STANDBY: return "STANDBY";
        default: return "?";
    }
}

// Thread safe.
char const * TransmitCarrierCalSm_event_id_to_string(TransmitCarrierCalSm_EventId id)
{
    switch (id)
    {
        case TransmitCarrierCalSm_EventId_AUTO: return "AUTO";
        case TransmitCarrierCalSm_EventId_AUTO_COMPLETE: return "AUTO_COMPLETE";
        case TransmitCarrierCalSm_EventId_DO: return "DO";
        case TransmitCarrierCalSm_EventId_FIND_MINIMUM: return "FIND_MINIMUM";
        case TransmitCarrierCalSm_EventId_MIN_EXIT: return "MIN_EXIT";
        case TransmitCarrierCalSm_EventId_NEXT_POINT: return "NEXT_POINT";
        case TransmitCarrierCalSm_EventId_READ_DELTA: return "READ_DELTA";
        default: return "?";
    }
}
