// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#ifndef UISM_H
#define UISM_H
#include <stdint.h>
#include <stdint.h> // for count var
#include "Mode.h"
//#include "SDT.h"


typedef enum UISm_EventId
{
    UISm_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    UISm_EventId_BIT = 1,
    UISm_EventId_CALIBRATE_FREQUENCY = 2,
    UISm_EventId_CALIBRATE_POWER = 3,
    UISm_EventId_CALIBRATE_RX_IQ = 4,
    UISm_EventId_CALIBRATE_TX_IQ = 5,
    UISm_EventId_DFE = 6,
    UISm_EventId_EQUALIZER = 7,
    UISm_EventId_HOME = 8,
    UISm_EventId_MENU = 9,
    UISm_EventId_SELECT = 10
} UISm_EventId;

enum
{
    UISm_EventIdCount = 11
};

typedef enum UISm_StateId
{
    UISm_StateId_ROOT = 0,
    UISm_StateId_BIT = 1,
    UISm_StateId_CALIBRATE_FREQUENCY = 2,
    UISm_StateId_CALIBRATE_POWER = 3,
    UISm_StateId_CALIBRATE_RX_IQ = 4,
    UISm_StateId_CALIBRATE_TX_IQ = 5,
    UISm_StateId_EQUALIZER = 6,
    UISm_StateId_FREQ_ENTRY = 7,
    UISm_StateId_HOME = 8,
    UISm_StateId_MAIN_MENU = 9,
    UISm_StateId_SECONDARY_MENU = 10,
    UISm_StateId_SPLASH = 11,
    UISm_StateId_UPDATE = 12
} UISm_StateId;

enum
{
    UISm_StateIdCount = 13
};


// Generated state machine
// forward declaration
typedef struct UISm UISm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct UISm_Vars
{
    bool clearScreen;
    uint16_t splashDuration_ms;
    uint16_t splashCount_ms;
    uint8_t mainMenuSelection;
    uint8_t mainMenuLength;
    uint8_t secondMenuSelection;
    uint8_t secondMenuLength;
    void *uiUp;
} UISm_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void UISm_ctor(UISm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void UISm_start(UISm* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void UISm_dispatch_event(UISm* sm, UISm_EventId event_id);

// Thread safe.
char const * UISm_state_id_to_string(UISm_StateId id);

// Thread safe.
char const * UISm_event_id_to_string(UISm_EventId id);

// Generated state machine
struct UISm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    UISm_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    UISm_Vars vars;
};

#endif // UISM_H
