// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "UISm.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
    

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(UISm* sm, UISm_StateId desired_state);

static void ROOT_enter(UISm* sm);

static void BIT_enter(UISm* sm);

static void BIT_exit(UISm* sm);

static void BIT_home(UISm* sm);

static void CALIBRATE_FREQUENCY_enter(UISm* sm);

static void CALIBRATE_FREQUENCY_exit(UISm* sm);

static void CALIBRATE_FREQUENCY_home(UISm* sm);

static void CALIBRATE_POWER_enter(UISm* sm);

static void CALIBRATE_POWER_exit(UISm* sm);

static void CALIBRATE_POWER_home(UISm* sm);

static void CALIBRATE_RX_IQ_enter(UISm* sm);

static void CALIBRATE_RX_IQ_exit(UISm* sm);

static void CALIBRATE_RX_IQ_home(UISm* sm);

static void CALIBRATE_TX_IQ_enter(UISm* sm);

static void CALIBRATE_TX_IQ_exit(UISm* sm);

static void CALIBRATE_TX_IQ_home(UISm* sm);

static void EQUALIZER_enter(UISm* sm);

static void EQUALIZER_exit(UISm* sm);

static void EQUALIZER_home(UISm* sm);

static void FREQ_ENTRY_enter(UISm* sm);

static void FREQ_ENTRY_exit(UISm* sm);

static void FREQ_ENTRY_home(UISm* sm);

static void HOME_enter(UISm* sm);

static void HOME_exit(UISm* sm);

static void HOME_bit(UISm* sm);

static void HOME_calibrate_frequency(UISm* sm);

static void HOME_calibrate_power(UISm* sm);

static void HOME_calibrate_rx_iq(UISm* sm);

static void HOME_calibrate_tx_iq(UISm* sm);

static void HOME_dfe(UISm* sm);

static void HOME_equalizer(UISm* sm);

static void HOME_menu(UISm* sm);

static void MAIN_MENU_enter(UISm* sm);

static void MAIN_MENU_exit(UISm* sm);

static void MAIN_MENU_home(UISm* sm);

static void MAIN_MENU_select(UISm* sm);

static void SECONDARY_MENU_enter(UISm* sm);

static void SECONDARY_MENU_exit(UISm* sm);

static void SECONDARY_MENU_home(UISm* sm);

static void SECONDARY_MENU_select(UISm* sm);

static void SPLASH_enter(UISm* sm);

static void SPLASH_exit(UISm* sm);

static void SPLASH_do(UISm* sm);

static void UPDATE_enter(UISm* sm);

static void UPDATE_exit(UISm* sm);

static void UPDATE_home(UISm* sm);

static void UPDATE_select(UISm* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void UISm_ctor(UISm* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void UISm_start(UISm* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(SPLASH)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `SPLASH`.
            SPLASH_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void UISm_dispatch_event(UISm* sm, UISm_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: UISm
        case UISm_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: BIT
        case UISm_StateId_BIT:
            switch (event_id)
            {
                case UISm_EventId_HOME: BIT_home(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: CALIBRATE_FREQUENCY
        case UISm_StateId_CALIBRATE_FREQUENCY:
            switch (event_id)
            {
                case UISm_EventId_HOME: CALIBRATE_FREQUENCY_home(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: CALIBRATE_POWER
        case UISm_StateId_CALIBRATE_POWER:
            switch (event_id)
            {
                case UISm_EventId_HOME: CALIBRATE_POWER_home(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: CALIBRATE_RX_IQ
        case UISm_StateId_CALIBRATE_RX_IQ:
            switch (event_id)
            {
                case UISm_EventId_HOME: CALIBRATE_RX_IQ_home(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: CALIBRATE_TX_IQ
        case UISm_StateId_CALIBRATE_TX_IQ:
            switch (event_id)
            {
                case UISm_EventId_HOME: CALIBRATE_TX_IQ_home(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: EQUALIZER
        case UISm_StateId_EQUALIZER:
            switch (event_id)
            {
                case UISm_EventId_HOME: EQUALIZER_home(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: FREQ_ENTRY
        case UISm_StateId_FREQ_ENTRY:
            switch (event_id)
            {
                case UISm_EventId_HOME: FREQ_ENTRY_home(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: HOME
        case UISm_StateId_HOME:
            switch (event_id)
            {
                case UISm_EventId_MENU: HOME_menu(sm); break;
                case UISm_EventId_CALIBRATE_RX_IQ: HOME_calibrate_rx_iq(sm); break;
                case UISm_EventId_DFE: HOME_dfe(sm); break;
                case UISm_EventId_CALIBRATE_TX_IQ: HOME_calibrate_tx_iq(sm); break;
                case UISm_EventId_CALIBRATE_FREQUENCY: HOME_calibrate_frequency(sm); break;
                case UISm_EventId_CALIBRATE_POWER: HOME_calibrate_power(sm); break;
                case UISm_EventId_EQUALIZER: HOME_equalizer(sm); break;
                case UISm_EventId_BIT: HOME_bit(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: MAIN_MENU
        case UISm_StateId_MAIN_MENU:
            switch (event_id)
            {
                case UISm_EventId_HOME: MAIN_MENU_home(sm); break;
                case UISm_EventId_SELECT: MAIN_MENU_select(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: SECONDARY_MENU
        case UISm_StateId_SECONDARY_MENU:
            switch (event_id)
            {
                case UISm_EventId_HOME: SECONDARY_MENU_home(sm); break;
                case UISm_EventId_SELECT: SECONDARY_MENU_select(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: SPLASH
        case UISm_StateId_SPLASH:
            switch (event_id)
            {
                case UISm_EventId_DO: SPLASH_do(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: UPDATE
        case UISm_StateId_UPDATE:
            switch (event_id)
            {
                case UISm_EventId_HOME: UPDATE_home(sm); break;
                case UISm_EventId_SELECT: UPDATE_select(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(UISm* sm, UISm_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case UISm_StateId_BIT: BIT_exit(sm); break;
            
            case UISm_StateId_CALIBRATE_FREQUENCY: CALIBRATE_FREQUENCY_exit(sm); break;
            
            case UISm_StateId_CALIBRATE_POWER: CALIBRATE_POWER_exit(sm); break;
            
            case UISm_StateId_CALIBRATE_RX_IQ: CALIBRATE_RX_IQ_exit(sm); break;
            
            case UISm_StateId_CALIBRATE_TX_IQ: CALIBRATE_TX_IQ_exit(sm); break;
            
            case UISm_StateId_EQUALIZER: EQUALIZER_exit(sm); break;
            
            case UISm_StateId_FREQ_ENTRY: FREQ_ENTRY_exit(sm); break;
            
            case UISm_StateId_HOME: HOME_exit(sm); break;
            
            case UISm_StateId_MAIN_MENU: MAIN_MENU_exit(sm); break;
            
            case UISm_StateId_SECONDARY_MENU: SECONDARY_MENU_exit(sm); break;
            
            case UISm_StateId_SPLASH: SPLASH_exit(sm); break;
            
            case UISm_StateId_UPDATE: UPDATE_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state BIT
////////////////////////////////////////////////////////////////////////////////

static void BIT_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_BIT;
    
    // BIT behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for BIT
}

static void BIT_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void BIT_home(UISm* sm)
{
    // BIT behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        BIT_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for BIT
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state CALIBRATE_FREQUENCY
////////////////////////////////////////////////////////////////////////////////

static void CALIBRATE_FREQUENCY_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_CALIBRATE_FREQUENCY;
    
    // CALIBRATE_FREQUENCY behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for CALIBRATE_FREQUENCY
}

static void CALIBRATE_FREQUENCY_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void CALIBRATE_FREQUENCY_home(UISm* sm)
{
    // CALIBRATE_FREQUENCY behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        CALIBRATE_FREQUENCY_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for CALIBRATE_FREQUENCY
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state CALIBRATE_POWER
////////////////////////////////////////////////////////////////////////////////

static void CALIBRATE_POWER_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_CALIBRATE_POWER;
    
    // CALIBRATE_POWER behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for CALIBRATE_POWER
}

static void CALIBRATE_POWER_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void CALIBRATE_POWER_home(UISm* sm)
{
    // CALIBRATE_POWER behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        CALIBRATE_POWER_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for CALIBRATE_POWER
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state CALIBRATE_RX_IQ
////////////////////////////////////////////////////////////////////////////////

static void CALIBRATE_RX_IQ_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_CALIBRATE_RX_IQ;
    
    // CALIBRATE_RX_IQ behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for CALIBRATE_RX_IQ
}

static void CALIBRATE_RX_IQ_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void CALIBRATE_RX_IQ_home(UISm* sm)
{
    // CALIBRATE_RX_IQ behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        CALIBRATE_RX_IQ_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for CALIBRATE_RX_IQ
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state CALIBRATE_TX_IQ
////////////////////////////////////////////////////////////////////////////////

static void CALIBRATE_TX_IQ_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_CALIBRATE_TX_IQ;
    
    // CALIBRATE_TX_IQ behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for CALIBRATE_TX_IQ
}

static void CALIBRATE_TX_IQ_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void CALIBRATE_TX_IQ_home(UISm* sm)
{
    // CALIBRATE_TX_IQ behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        CALIBRATE_TX_IQ_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for CALIBRATE_TX_IQ
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state EQUALIZER
////////////////////////////////////////////////////////////////////////////////

static void EQUALIZER_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_EQUALIZER;
    
    // EQUALIZER behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for EQUALIZER
}

static void EQUALIZER_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void EQUALIZER_home(UISm* sm)
{
    // EQUALIZER behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        EQUALIZER_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for EQUALIZER
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FREQ_ENTRY
////////////////////////////////////////////////////////////////////////////////

static void FREQ_ENTRY_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_FREQ_ENTRY;
    
    // FREQ_ENTRY behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for FREQ_ENTRY
}

static void FREQ_ENTRY_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void FREQ_ENTRY_home(UISm* sm)
{
    // FREQ_ENTRY behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        FREQ_ENTRY_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for FREQ_ENTRY
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state HOME
////////////////////////////////////////////////////////////////////////////////

static void HOME_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_HOME;
    
    // HOME behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for HOME
}

static void HOME_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void HOME_bit(UISm* sm)
{
    // HOME behavior
    // uml: BIT TransitionTo(BIT)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `BIT`.
        BIT_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME
    
    // No ancestor handles this event.
}

static void HOME_calibrate_frequency(UISm* sm)
{
    // HOME behavior
    // uml: CALIBRATE_FREQUENCY TransitionTo(CALIBRATE_FREQUENCY)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `CALIBRATE_FREQUENCY`.
        CALIBRATE_FREQUENCY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME
    
    // No ancestor handles this event.
}

static void HOME_calibrate_power(UISm* sm)
{
    // HOME behavior
    // uml: CALIBRATE_POWER TransitionTo(CALIBRATE_POWER)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `CALIBRATE_POWER`.
        CALIBRATE_POWER_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME
    
    // No ancestor handles this event.
}

static void HOME_calibrate_rx_iq(UISm* sm)
{
    // HOME behavior
    // uml: CALIBRATE_RX_IQ TransitionTo(CALIBRATE_RX_IQ)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `CALIBRATE_RX_IQ`.
        CALIBRATE_RX_IQ_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME
    
    // No ancestor handles this event.
}

static void HOME_calibrate_tx_iq(UISm* sm)
{
    // HOME behavior
    // uml: CALIBRATE_TX_IQ TransitionTo(CALIBRATE_TX_IQ)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `CALIBRATE_TX_IQ`.
        CALIBRATE_TX_IQ_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME
    
    // No ancestor handles this event.
}

static void HOME_dfe(UISm* sm)
{
    // HOME behavior
    // uml: DFE TransitionTo(FREQ_ENTRY)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `FREQ_ENTRY`.
        FREQ_ENTRY_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME
    
    // No ancestor handles this event.
}

static void HOME_equalizer(UISm* sm)
{
    // HOME behavior
    // uml: EQUALIZER TransitionTo(EQUALIZER)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `EQUALIZER`.
        EQUALIZER_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME
    
    // No ancestor handles this event.
}

static void HOME_menu(UISm* sm)
{
    // HOME behavior
    // uml: MENU TransitionTo(MAIN_MENU)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        HOME_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `MAIN_MENU`.
        MAIN_MENU_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for HOME
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MAIN_MENU
////////////////////////////////////////////////////////////////////////////////

static void MAIN_MENU_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_MAIN_MENU;
    
    // MAIN_MENU behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for MAIN_MENU
}

static void MAIN_MENU_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void MAIN_MENU_home(UISm* sm)
{
    // MAIN_MENU behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        MAIN_MENU_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for MAIN_MENU
    
    // No ancestor handles this event.
}

static void MAIN_MENU_select(UISm* sm)
{
    // MAIN_MENU behavior
    // uml: SELECT TransitionTo(SECONDARY_MENU)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        MAIN_MENU_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `SECONDARY_MENU`.
        SECONDARY_MENU_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for MAIN_MENU
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SECONDARY_MENU
////////////////////////////////////////////////////////////////////////////////

static void SECONDARY_MENU_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_SECONDARY_MENU;
    
    // SECONDARY_MENU behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for SECONDARY_MENU
}

static void SECONDARY_MENU_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void SECONDARY_MENU_home(UISm* sm)
{
    // SECONDARY_MENU behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        SECONDARY_MENU_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for SECONDARY_MENU
    
    // No ancestor handles this event.
}

static void SECONDARY_MENU_select(UISm* sm)
{
    // SECONDARY_MENU behavior
    // uml: SELECT TransitionTo(UPDATE)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        SECONDARY_MENU_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `UPDATE`.
        UPDATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for SECONDARY_MENU
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SPLASH
////////////////////////////////////////////////////////////////////////////////

static void SPLASH_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_SPLASH;
    
    // SPLASH behavior
    // uml: enter / { splashCount_ms = 0; }
    {
        // Step 1: execute action `splashCount_ms = 0;`
        sm->vars.splashCount_ms = 0;
    } // end of behavior for SPLASH
}

static void SPLASH_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void SPLASH_do(UISm* sm)
{
    // SPLASH behavior
    // uml: 1. do / { splashCount_ms++; }
    {
        // Step 1: execute action `splashCount_ms++;`
        sm->vars.splashCount_ms++;
    } // end of behavior for SPLASH
    
    // SPLASH behavior
    // uml: do [splashCount_ms >= splashDuration_ms] TransitionTo(HOME)
    if (sm->vars.splashCount_ms >= sm->vars.splashDuration_ms)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        SPLASH_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for SPLASH
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state UPDATE
////////////////////////////////////////////////////////////////////////////////

static void UPDATE_enter(UISm* sm)
{
    sm->state_id = UISm_StateId_UPDATE;
    
    // UPDATE behavior
    // uml: enter / { clearScreen = true; }
    {
        // Step 1: execute action `clearScreen = true;`
        sm->vars.clearScreen = true;
    } // end of behavior for UPDATE
}

static void UPDATE_exit(UISm* sm)
{
    sm->state_id = UISm_StateId_ROOT;
}

static void UPDATE_home(UISm* sm)
{
    // UPDATE behavior
    // uml: HOME TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        UPDATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for UPDATE
    
    // No ancestor handles this event.
}

static void UPDATE_select(UISm* sm)
{
    // UPDATE behavior
    // uml: SELECT TransitionTo(HOME)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        UPDATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `HOME`.
        HOME_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for UPDATE
    
    // No ancestor handles this event.
}

// Thread safe.
char const * UISm_state_id_to_string(UISm_StateId id)
{
    switch (id)
    {
        case UISm_StateId_ROOT: return "ROOT";
        case UISm_StateId_BIT: return "BIT";
        case UISm_StateId_CALIBRATE_FREQUENCY: return "CALIBRATE_FREQUENCY";
        case UISm_StateId_CALIBRATE_POWER: return "CALIBRATE_POWER";
        case UISm_StateId_CALIBRATE_RX_IQ: return "CALIBRATE_RX_IQ";
        case UISm_StateId_CALIBRATE_TX_IQ: return "CALIBRATE_TX_IQ";
        case UISm_StateId_EQUALIZER: return "EQUALIZER";
        case UISm_StateId_FREQ_ENTRY: return "FREQ_ENTRY";
        case UISm_StateId_HOME: return "HOME";
        case UISm_StateId_MAIN_MENU: return "MAIN_MENU";
        case UISm_StateId_SECONDARY_MENU: return "SECONDARY_MENU";
        case UISm_StateId_SPLASH: return "SPLASH";
        case UISm_StateId_UPDATE: return "UPDATE";
        default: return "?";
    }
}

// Thread safe.
char const * UISm_event_id_to_string(UISm_EventId id)
{
    switch (id)
    {
        case UISm_EventId_BIT: return "BIT";
        case UISm_EventId_CALIBRATE_FREQUENCY: return "CALIBRATE_FREQUENCY";
        case UISm_EventId_CALIBRATE_POWER: return "CALIBRATE_POWER";
        case UISm_EventId_CALIBRATE_RX_IQ: return "CALIBRATE_RX_IQ";
        case UISm_EventId_CALIBRATE_TX_IQ: return "CALIBRATE_TX_IQ";
        case UISm_EventId_DFE: return "DFE";
        case UISm_EventId_DO: return "DO";
        case UISm_EventId_EQUALIZER: return "EQUALIZER";
        case UISm_EventId_HOME: return "HOME";
        case UISm_EventId_MENU: return "MENU";
        case UISm_EventId_SELECT: return "SELECT";
        default: return "?";
    }
}
